{ pkgs, odd }:

let
  # TEI P5 version. Deliberately duplicated in <repo-root>/nix/tei.nix (separate
  # flake). Drift is caught by the `monorepo-tei-version-coherence` check. Bump
  # both together.
  teiP5Version = "4.11.0";

  teiAllSchema = pkgs.fetchurl {
    url = "https://www.tei-c.org/Vault/P5/${teiP5Version}/xml/tei/custom/schema/relaxng/tei_all.rng";
    hash = "sha256-7MSfAMN/SQtd9xa2cuPbpjXrHknM2I+5aYWUmN9CwIQ=";
  };

  teiStylesheets = pkgs.fetchzip {
    url = "https://github.com/TEIC/Stylesheets/releases/download/v7.60.0/tei-xsl-7.60.0.zip";
    hash = "sha256-KcDZmMNtJHFbaBlTgr37Yy6O6J/QLDcoAG20CmBDpKk=";
    stripRoot = false;
  };

  teiP5Subset = pkgs.fetchurl {
    url = "https://www.tei-c.org/Vault/P5/${teiP5Version}/xml/tei/odd/p5subset.xml";
    hash = "sha256-r9HruHPKcY1hvly09hFkoRA3/gybYSomI+avGvGe8wE=";
  };

  generator = "TEI Stylesheets 7.60.0 with Saxon-HE ${pkgs.saxon-he.version}";
  generatorBuildHash =
    "sha256:"
    + builtins.hashString "sha256" (
      builtins.toJSON {
        recipe = builtins.hashFile "sha256" ./tei-profile-artifacts.nix;
        stylesheets = toString teiStylesheets;
        p5Subset = toString teiP5Subset;
        saxon = toString pkgs.saxon-he;
        sed = toString pkgs.gnused;
        awk = toString pkgs.gawk;
        coreutils = toString pkgs.coreutils;
        jq = toString pkgs.jq;
      }
    );

  artifacts =
    pkgs.runCommand "abc-tei-profile-artifacts"
      {
        nativeBuildInputs = [
          pkgs.saxon-he
          pkgs.gnused
          pkgs.gawk
          pkgs.jq
        ];
      }
      ''
        set -euo pipefail
        cp ${odd} tei-profile.odd
        saxon-he -s:tei-profile.odd \
          -xsl:${teiStylesheets}/xml/tei/stylesheet/odds/odd2odd.xsl \
          -o:expanded.odd \
          defaultSource=${teiP5Subset}
        saxon-he -s:expanded.odd \
          -xsl:${teiStylesheets}/xml/tei/stylesheet/odds/odd2relax.xsl \
          -o:tei-profile.rng
        saxon-he -s:expanded.odd \
          -xsl:${teiStylesheets}/xml/tei/stylesheet/odds/extract-isosch.xsl \
          -o:tei-profile.sch \
          lang=en
        # Build-artifact canonicalization uses narrow rewrites; the
        # ODD remains source of truth.
        # 1. Strip non-deterministic generation timestamps so rebuilds are
        #    byte-stable.
        # 2. Rewrite profile pattern IDs from
        #    `schematron-constraint-<ident>-<seq>` back to the `<ident>` the
        #    ODD's constraintSpec/@ident declared. Inherited TEI built-in
        #    pattern IDs are left untouched.
        sed -E -i 's|Schema generated from ODD source [0-9TZ:.+-]+\. \. ?|Schema generated from ODD source. |' tei-profile.rng
        sed -E -i "s|<!-- This file generated [0-9TZ:.+-]+ by 'extract-isosch.xsl'. -->|<!-- This file generated by 'extract-isosch.xsl'. -->|" tei-profile.sch
        sed -E -i 's|id="schematron-constraint-(abc-[a-z0-9-]+)-[0-9]+"|id="\1"|g' tei-profile.sch
        sed -E -i 's|id="abc-tei-v0-(abc-[a-z0-9-]+)-constraint-rule-[0-9]+"|id="\1"|g' tei-profile.sch tei-profile.rng
        # Drop inherited TEI built-in patterns that the ODD did not declare.
        # The committed Schematron contains only explicitly declared profile policy.
        # This also preserves compatibility with
        # ph-schematron's stricter pure ISO model, which rejects the inherited
        # TEI sch:let / role="nonfatal" constructs even though the XSLT path can
        # execute them.
        awk '
          /^   <pattern id="schematron-constraint-/ { drop = 1 }
          !drop { print }
          drop && /^   <\/pattern>/ { drop = 0 }
        ' tei-profile.sch > tei-profile.sch.filtered
        mv tei-profile.sch.filtered tei-profile.sch
        mkdir -p "$out"
        cp tei-profile.rng tei-profile.sch "$out/"
        jq -nS \
          --arg generator ${pkgs.lib.escapeShellArg generator} \
          --arg generator_build_hash ${pkgs.lib.escapeShellArg generatorBuildHash} \
          --arg odd_hash "sha256:$(sha256sum tei-profile.odd | cut -d ' ' -f 1)" \
          --arg rng_hash "sha256:$(sha256sum tei-profile.rng | cut -d ' ' -f 1)" \
          --arg schematron_hash "sha256:$(sha256sum tei-profile.sch | cut -d ' ' -f 1)" \
          '{generator: $generator, generator_build_hash: $generator_build_hash,
            odd_hash: $odd_hash, rng_hash: $rng_hash, schematron_hash: $schematron_hash}' \
          > "$out/tei-profile-generation.json"
      '';
in
{
  version = teiP5Version;
  inherit
    teiAllSchema
    teiStylesheets
    teiP5Subset
    artifacts
    ;
}
