(ns abc.tools.facts
  "Layer C fact emitter. Reads REAL manifests / drift events / person records
  and writes Prolog facts to a target directory. Identity hashes are computed
  here via the real manifest/artifact-id function — Prolog only compares
  emitted facts, never recomputes identity. (Design spec §7.3: avoid hidden
  hand-translation in Prolog.) The committed facts under
  fixtures/v0/facts/prolog/ are byte-stable (sorted) and regenerated by this
  emitter; clj-nix-focused-tests byte-compares committed vs freshly-emitted."
  (:require [abc.tools.files :as files]
            [abc.tools.manifest :as manifest]
            [babashka.fs :as fs]
            [clojure.string :as str]
            [clojure.java.io :as io]))

(def ^:private example-manifests
  ["examples/v0/example-work/manifest.json"])

(def ^:private example-drift-events-dir
  "examples/v0/example-persons/_events")

(def ^:private example-persons-dir
  "examples/v0/example-persons")

(def ^:private example-persons-index-dir
  ;; person-drift-index files bridge drift participants back to person_id;
  ;; abc-... person_ids that drift successors reference live here (not as
  ;; top-level records). Reading both sources keeps the referential-integrity
  ;; gate (Task 7) honest: it does not dangle on the real corpus.
  "examples/v0/example-persons/_indexes")

;; All Prolog string args are emitted as single-quoted atoms with ' doubled.
;; This is CRITICAL: bare 000879 parses as the integer 879, and
;; abc-000000000001 parses as the arithmetic expression abc-1. Real IDs
;; (person_id, artifact_id, drift_event_id, manifest_path) are strings —
;; quote them or the facts lose identity.
(defn- prolog-atom [s]
  (str "'" (.replace (str s) "'" "''") "'"))

(defn- ensure-dir! [out-dir]
  (fs/create-dirs out-dir))

(defn- write-lines! [out-dir filename lines]
  ;; Sort for byte-stability across .listFiles orderings (plan Blocker
  ;; remediation). Empty corpus writes an empty file (not none), so downstream
  ;; swipl -c finds the file regardless of corpus size.
  (spit (io/file out-dir filename) (str/join "\n" (sort lines)) :append false))

(defn- append-lines!
  ;; Append a (sorted, deduped) fact block to an existing fact file, preceded
  ;; by a comment header. Used so person_records.pl carries both
  ;; person_record/1 and drift_successor/2 (Task 7 queries both).
  [out-dir filename header lines]
  (let [existing (slurp (io/file out-dir filename))
        addition (when (seq lines)
                   (str "\n\n% " header "\n" (str/join "\n" (sort lines))))]
    (spit (io/file out-dir filename) (str existing addition))))

(defn- emit-manifest-identity-facts! [out-dir]
  (let [lines (for [path example-manifests
                    :let [m (files/read-json path)
                          id-obj (get m "manifest_identity_object")
                          hash (manifest/artifact-id id-obj)]]
                (format "manifest_identity(%s, %s)."
                        (prolog-atom path) (prolog-atom hash)))]
    (write-lines! out-dir "manifest_identity.pl" lines)))

(defn- emit-drift-facts! [out-dir]
  (let [dir (fs/file example-drift-events-dir)
        event-files (->> (if (fs/directory? dir) (fs/list-dir dir) [])
                         (filter fs/regular-file?)
                         (sort-by (comp str fs/file-name))
                         (map fs/file))
        lines (for [f event-files
                    :let [ev (files/read-json f)
                          id (get ev "drift_event_id")]]
                (format "drift_event(%s)." (prolog-atom id)))]
    (write-lines! out-dir "drift.pl" lines)))

(defn- snapshot->person-id [event]
  ;; snapshot_id -> person_id, for resolving prov.used (predecessors) and
  ;; prov.was_generated_by (successors) back to person_id via participants[].
  (into {} (for [p (get event "participants")]
             [(get p "snapshot_id") (get p "person_id")])))

(defn- person-record-ids
  ;; Union of person_ids present as top-level records AND as drift-index
  ;; entries. Both assert a person exists in the corpus; the union is what
  ;; the referential-integrity query (Task 7) resolves against.
  []
  (let [records-dir (fs/file example-persons-dir)
        indexes-dir (fs/file example-persons-index-dir)
        records (->> (if (fs/directory? records-dir) (fs/list-dir records-dir) [])
                     (filter fs/regular-file?)
                     (filter #(str/ends-with? (str (fs/file-name %)) ".json"))
                     (sort-by (comp str fs/file-name))
                     (map fs/file))
        indexes (->> (if (fs/directory? indexes-dir) (fs/list-dir indexes-dir) [])
                     (filter fs/regular-file?)
                     (sort-by (comp str fs/file-name))
                     (map fs/file))
        extract (fn [f] (get (files/read-json f) "person_id"))]
    (into [] (comp (map extract)
                   (remove nil?)
                   (distinct))
          (concat records indexes))))

(defn- emit-person-record-facts! [out-dir]
  (let [record-lines (for [pid (person-record-ids)]
                       (format "person_record(%s)." (prolog-atom pid)))
        event-dir (fs/file example-drift-events-dir)
        event-files (->> (if (fs/directory? event-dir) (fs/list-dir event-dir) [])
                         (filter fs/regular-file?)
                         (sort-by (comp str fs/file-name))
                         (map fs/file))
        ;; drift_successor/2: for each drift event, every post- participant
        ;; (successor) is a successor of every pre- participant (predecessor).
        ;; Resolved by mapping prov.used (pre snapshot_ids) and
        ;; prov.was_generated_by (post snapshot_ids) through participants to
        ;; person_ids. Real corpus is the source — no hand-transcription.
        successor-lines (for [f event-files
                              :let [ev (files/read-json f)
                                    snap->pid (snapshot->person-id ev)
                                    pre-pids (for [s (get-in ev ["prov" "used"])]
                                               (get snap->pid s))
                                    post-pids (for [s (get-in ev ["prov" "was_generated_by"])]
                                                (get snap->pid s))
                                    pre (set (remove nil? pre-pids))
                                    post (set (remove nil? post-pids))]
                              succ post
                              pred pre]
                          (format "drift_successor(%s, %s)."
                                  (prolog-atom pred) (prolog-atom succ)))]
    (write-lines! out-dir "person_records.pl" record-lines)
    (append-lines! out-dir "person_records.pl"
                   "drift_successor/2 emitted from prov.used / was_generated_by"
                   successor-lines)))

(defn emit-prolog!
  "Read real corpus (manifests, drift events, person records + indexes) and
  write Prolog facts to out-dir. Arity-1: out-dir is a string path. Creates
  the directory if absent. Returns nil."
  [out-dir]
  (ensure-dir! out-dir)
  (emit-manifest-identity-facts! out-dir)
  (emit-drift-facts! out-dir)
  (emit-person-record-facts! out-dir))
