{
  description = "Aozora Bunko Converter development environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    local-pkgs = {
      url = "path:/home/bor/Projects/nix/pkgs";
      flake = false;
    };
    tei-eaj-aozora-tei = {
      url = "github:TEI-EAJ/aozora_tei";
      flake = false;
    };
    clj-nix = {
      url = "github:jlesquembre/clj-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    crane = {
      url = "github:ipetkov/crane/v0.23.4";
    };
  };

  outputs =
    {
      nixpkgs,
      local-pkgs,
      tei-eaj-aozora-tei,
      clj-nix,
      crane,
      ...
    }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];

      forAllSystems = nixpkgs.lib.genAttrs systems;
      localPkgsOverlay =
        final: _prev:
        import local-pkgs {
          pkgs = final;
          craneLib = crane.mkLib final;
        };
    in
    {
      formatter = forAllSystems (
        system:
        let
          pkgs = import nixpkgs { inherit system; };
        in
        pkgs.nixfmt
      );

      apps = forAllSystems (
        system:
        let
          pkgs = import nixpkgs {
            inherit system;
            overlays = [
              clj-nix.overlays.default
              localPkgsOverlay
            ];
          };
          tei-schema = pkgs.fetchurl {
            url = "https://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng";
            hash = "sha256-7MSfAMN/SQtd9xa2cuPbpjXrHknM2I+5aYWUmN9CwIQ=";
          };
          tei-stylesheets = pkgs.fetchzip {
            url = "https://github.com/TEIC/Stylesheets/releases/download/v7.60.0/tei-xsl-7.60.0.zip";
            hash = "sha256-KcDZmMNtJHFbaBlTgr37Yy6O6J/QLDcoAG20CmBDpKk=";
            stripRoot = false;
          };
          tei-p5subset = pkgs.fetchurl {
            url = "https://www.tei-c.org/Vault/P5/4.11.0/xml/tei/odd/p5subset.xml";
            hash = "sha256-r9HruHPKcY1hvly09hFkoRA3/gybYSomI+avGvGe8wE=";
          };
          tei-profile-artifacts =
            pkgs.runCommand "abc-tei-profile-artifacts"
              {
                nativeBuildInputs = [
                  pkgs.saxon-he
                  pkgs.gnused
                ];
              }
              ''
                set -euo pipefail
                cp ${./schemas/tei-profile.odd} tei-profile.odd
                saxon-he -s:tei-profile.odd \
                  -xsl:${tei-stylesheets}/xml/tei/stylesheet/odds/odd2odd.xsl \
                  -o:expanded.odd \
                  defaultSource=${tei-p5subset}
                saxon-he -s:expanded.odd \
                  -xsl:${tei-stylesheets}/xml/tei/stylesheet/odds/odd2relax.xsl \
                  -o:tei-profile.rng
                saxon-he -s:expanded.odd \
                  -xsl:${tei-stylesheets}/xml/tei/stylesheet/odds/extract-isosch.xsl \
                  -o:tei-profile.sch \
                  lang=en
                # Build-artifact canonicalization (ADR 0012). Two narrow
                # rewrites; the ODD remains source of truth.
                # 1. Strip non-deterministic generation timestamps so
                #    rebuilds are byte-stable.
                # 2. Rewrite ABC pattern IDs from
                #    `schematron-constraint-<ident>-<seq>` back to the
                #    `<ident>` the ODD's constraintSpec/@ident declared.
                #    Inherited TEI built-in pattern IDs are left untouched.
                sed -E -i 's|Schema generated from ODD source [0-9TZ:.+-]+\. \. ?|Schema generated from ODD source. |' tei-profile.rng
                sed -E -i "s|<!-- This file generated [0-9TZ:.+-]+ by 'extract-isosch.xsl'. -->|<!-- This file generated by 'extract-isosch.xsl'. -->|" tei-profile.sch
                sed -E -i 's|id="schematron-constraint-(abc-[a-z0-9-]+)-[0-9]+"|id="\1"|g' tei-profile.sch
                # Drop inherited TEI built-in patterns that the ODD did not
                # declare. The ABC v0 Schematron evaluator (abc.tools.schematron)
                # is a minimal subset and does not implement sch:let or other
                # features used by the inherited TEI corpus. The 7 ABC
                # constraintSpec rules are the committed contract surface.
                awk '
                  /^   <pattern id="schematron-constraint-/ { drop = 1 }
                  !drop { print }
                  drop && /^   <\/pattern>/ { drop = 0 }
                ' tei-profile.sch > tei-profile.sch.filtered
                mv tei-profile.sch.filtered tei-profile.sch
                mkdir -p "$out"
                cp tei-profile.rng tei-profile.sch "$out/"
              '';
        in
        {
          validate-design-bundle = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-validate-design-bundle" ''
                export PATH="${
                  pkgs.lib.makeBinPath [
                    pkgs.git-cliff
                    pkgs.libxml2
                  ]
                }:''${PATH:-}"
                export TEI_SCHEMA_PATH="${tei-schema}"
                exec ${pkgs.clojure}/bin/clojure -M:abc/validate-design-bundle "$@"
              ''
            );
            meta.description = "Validate ABC v0 design-bundle schemas and fixtures";
          };

          materialize-import = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-materialize-import" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/materialize-import "$@"
              ''
            );
            meta.description = "Materialize imported ab-validator output as ABC manifests";
          };

          materialize-publication = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-materialize-publication" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/materialize-publication "$@"
              ''
            );
            meta.description = "Materialize parser-IR publication plaintext and TEI artifacts";
          };

          materialize-source-snapshot = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-materialize-source-snapshot" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/materialize-source-snapshot "$@"
              ''
            );
            meta.description = "Materialize a source corpus snapshot and source manifests";
          };

          manifest-to-rdf = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-manifest-to-rdf" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/manifest-to-rdf "$@"
              ''
            );
            meta.description = "Generate deterministic RDF/Turtle view from an ABC manifest";
          };

          aozora-ingest = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-aozora-ingest" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/aozora-ingest "$@"
              ''
            );
            meta.description = "Build a metadata-record JSON from an Aozora list_person_all_extended ZIP slice";
          };

          validate-corpus = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-validate-corpus" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/validate-corpus "$@"
              ''
            );
            meta.description = "Validate an ingested corpus directory through SHACL";
          };

          person-drift-history = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-person-drift-history" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/person-drift-history "$@"
              ''
            );
            meta.description = "Audit generated corpus snapshots for conservative person split/merge candidates";
          };

          aozora-history-audit = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-aozora-history-audit" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/aozora-history-audit "$@"
              ''
            );
            meta.description = "Extract two Aozora git refs, ingest them, validate current corpus, and report person drift candidates";
          };

          aozora-upstream-audit = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-aozora-upstream-audit" ''
                set -euo pipefail
                if [ ! -d examples/v0/example-persons ]; then
                  echo "aozora-upstream-audit: run from the ABC repository root; examples/v0/example-persons not found" >&2
                  exit 2
                fi
                exec ${pkgs.clojure}/bin/clojure -M:abc/aozora-history-audit \
                  --drift-persons-dir examples/v0/example-persons \
                  --fail-on-candidates \
                  --fail-on-drift-participant-updates \
                  "$@"
              ''
            );
            meta.description = "Default after-upstream Aozora audit with drift sidecars and failure gates enabled";
          };

          regenerate-tei-profile = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-regenerate-tei-profile" ''
                set -euo pipefail
                target="''${1:-$PWD}"
                if [ ! -d "$target/schemas" ]; then
                  echo "regenerate-tei-profile: $target/schemas not found" >&2
                  echo "usage: nix run .#regenerate-tei-profile [-- <repo-root>]" >&2
                  exit 2
                fi
                install -m 0644 "${tei-profile-artifacts}/tei-profile.rng" "$target/schemas/tei-profile.rng"
                install -m 0644 "${tei-profile-artifacts}/tei-profile.sch" "$target/schemas/tei-profile.sch"
                echo "Updated $target/schemas/tei-profile.{rng,sch} from schemas/tei-profile.odd."
              ''
            );
            meta.description = "Regenerate schemas/tei-profile.{rng,sch} from schemas/tei-profile.odd via TEI Stylesheets";
          };

          tei-eaj-aozora-tei-source = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-tei-eaj-aozora-tei-source" ''
                printf '%s\n' ${tei-eaj-aozora-tei}
              ''
            );
            meta.description = "Print the pinned TEI-EAJ/aozora_tei comparison source path";
          };

          tei-eaj-aozora-melos-report = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-tei-eaj-aozora-melos-report" ''
                set -euo pipefail
                output="''${1:-docs/handoffs/tei-eaj-aozora-melos-comparison-report.md}"
                exec ${pkgs.python3}/bin/python3 ${./prototypes/tei-eaj-comparison/tei_eaj_compare.py} \
                  --report melos \
                  --abc paper/demo-melos-real/tei.xml \
                  --tei-eaj-root ${tei-eaj-aozora-tei} \
                  --source-rev 77a675fc2771936f9544505d922d4cd45075338c \
                  --output "$output"
              ''
            );
            meta.description = "Regenerate the ABC vs TEI-EAJ Melos comparison report";
          };

          tei-eaj-aozora-all-work-report = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-tei-eaj-aozora-all-work-report" ''
                set -euo pipefail
                output="''${1:-docs/handoffs/tei-eaj-aozora-all-work-comparison-report.md}"
                exec ${pkgs.python3}/bin/python3 ${./prototypes/tei-eaj-comparison/tei_eaj_compare.py} \
                  --report all-work \
                  --abc-tei-dir paper \
                  --tei-eaj-root ${tei-eaj-aozora-tei} \
                  --source-rev 77a675fc2771936f9544505d922d4cd45075338c \
                  --output "$output"
              ''
            );
            meta.description = "Regenerate the all-work ABC vs TEI-EAJ comparison report";
          };

          tei-eaj-aozora-reports = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-tei-eaj-aozora-reports" ''
                set -euo pipefail
                melos_output="''${1:-docs/handoffs/tei-eaj-aozora-melos-comparison-report.md}"
                all_work_output="''${2:-docs/handoffs/tei-eaj-aozora-all-work-comparison-report.md}"
                ${pkgs.python3}/bin/python3 ${./prototypes/tei-eaj-comparison/tei_eaj_compare.py} \
                  --report melos \
                  --abc paper/demo-melos-real/tei.xml \
                  --tei-eaj-root ${tei-eaj-aozora-tei} \
                  --source-rev 77a675fc2771936f9544505d922d4cd45075338c \
                  --output "$melos_output"
                ${pkgs.python3}/bin/python3 ${./prototypes/tei-eaj-comparison/tei_eaj_compare.py} \
                  --report all-work \
                  --abc-tei-dir paper \
                  --tei-eaj-root ${tei-eaj-aozora-tei} \
                  --source-rev 77a675fc2771936f9544505d922d4cd45075338c \
                  --output "$all_work_output"
                printf 'Updated %s\nUpdated %s\n' "$melos_output" "$all_work_output"
              ''
            );
            meta.description = "Regenerate both TEI-EAJ comparison reports";
          };
        }
      );

      checks = forAllSystems (
        system:
        let
          pkgs = import nixpkgs {
            inherit system;
            overlays = [
              clj-nix.overlays.default
              localPkgsOverlay
            ];
          };
          cljDepsCache = pkgs.mk-deps-cache {
            lockfile = ./deps-lock.json;
          };
          tei-stylesheets = pkgs.fetchzip {
            url = "https://github.com/TEIC/Stylesheets/releases/download/v7.60.0/tei-xsl-7.60.0.zip";
            hash = "sha256-KcDZmMNtJHFbaBlTgr37Yy6O6J/QLDcoAG20CmBDpKk=";
            stripRoot = false;
          };
          tei-p5subset = pkgs.fetchurl {
            url = "https://www.tei-c.org/Vault/P5/4.11.0/xml/tei/odd/p5subset.xml";
            hash = "sha256-r9HruHPKcY1hvly09hFkoRA3/gybYSomI+avGvGe8wE=";
          };
          tei-profile-artifacts =
            pkgs.runCommand "abc-tei-profile-artifacts"
              {
                nativeBuildInputs = [
                  pkgs.saxon-he
                  pkgs.gnused
                ];
              }
              ''
                set -euo pipefail
                cp ${./schemas/tei-profile.odd} tei-profile.odd
                saxon-he -s:tei-profile.odd \
                  -xsl:${tei-stylesheets}/xml/tei/stylesheet/odds/odd2odd.xsl \
                  -o:expanded.odd \
                  defaultSource=${tei-p5subset}
                saxon-he -s:expanded.odd \
                  -xsl:${tei-stylesheets}/xml/tei/stylesheet/odds/odd2relax.xsl \
                  -o:tei-profile.rng
                saxon-he -s:expanded.odd \
                  -xsl:${tei-stylesheets}/xml/tei/stylesheet/odds/extract-isosch.xsl \
                  -o:tei-profile.sch \
                  lang=en
                sed -E -i 's|Schema generated from ODD source [0-9TZ:.+-]+\. \. ?|Schema generated from ODD source. |' tei-profile.rng
                sed -E -i "s|<!-- This file generated [0-9TZ:.+-]+ by 'extract-isosch.xsl'. -->|<!-- This file generated by 'extract-isosch.xsl'. -->|" tei-profile.sch
                sed -E -i 's|id="schematron-constraint-(abc-[a-z0-9-]+)-[0-9]+"|id="\1"|g' tei-profile.sch
                # Drop inherited TEI built-in patterns that the ODD did not
                # declare. The ABC v0 Schematron evaluator (abc.tools.schematron)
                # is a minimal subset and does not implement sch:let or other
                # features used by the inherited TEI corpus. The 7 ABC
                # constraintSpec rules are the committed contract surface.
                awk '
                  /^   <pattern id="schematron-constraint-/ { drop = 1 }
                  !drop { print }
                  drop && /^   <\/pattern>/ { drop = 0 }
                ' tei-profile.sch > tei-profile.sch.filtered
                mv tei-profile.sch.filtered tei-profile.sch
                mkdir -p "$out"
                cp tei-profile.rng tei-profile.sch "$out/"
              '';
        in
        {
          clj-nix-focused-tests =
            pkgs.runCommand "abc-clj-nix-focused-tests"
              {
                nativeBuildInputs = [
                  pkgs.clojure
                  pkgs.git-cliff
                  pkgs.libxml2
                ];
              }
              ''
                cp -R ${./.} source
                chmod -R u+w source
                cd source
                cp ${./nix/clj-nix-deps.edn} deps.edn

                export HOME="${cljDepsCache}"
                export JAVA_TOOL_OPTIONS="-Duser.home=${cljDepsCache}"
                export CLJ_CONFIG="$HOME/.clojure"
                export CLJ_CACHE="$TMPDIR/cp-cache"
                export XDG_CONFIG_HOME="$TMPDIR/xdg-config"
                export GITLIBS="$HOME/.gitlibs"

                # The Nix sandbox has no network access; tests that need
                # the upstream TEI RelaxNG schema (fetched at app build
                # time, not at test time) skip cleanly when this flag is
                # set. End-to-end TEI validation runs via the
                # `nix run .#validate-design-bundle` app, not here.
                export ABC_TEI_SCHEMA_SKIP=1

                clojure -M:abc/focused-test

                mkdir -p "$out"
                echo "ABC focused Clojure tests passed with clj-nix dependency cache." > "$out/result.txt"
              '';

          aat-parser-ir-probe-tests =
            pkgs.runCommand "abc-aat-parser-ir-probe-tests"
              {
                nativeBuildInputs = [
                  pkgs.python3
                ];
              }
              ''
                cp -R ${./.} source
                chmod -R u+w source
                cd source

                python3 -m unittest prototypes/aat-to-parser-ir-probe/test_probe_mapping.py

                mkdir -p "$out"
                echo "AAT parser-IR probe tests passed." > "$out/result.txt"
              '';

          contract-surface = pkgs.runCommand "abc-contract-surface-check" { } ''
            test -f ${./resources/abc/ndc9.edn.xz}
            test -f ${./nix/clj-nix-deps.edn}
            test -f ${./deps-lock.json}
            test -f ${./src/abc/annotation/schema.clj}
            test -f ${./src/abc/text.clj}
            test -f ${./src/abc/ndc.clj}
            test -f ${./src/abc/tools/hash.clj}
            test -f ${./src/abc/tools/jcs.clj}
            test -f ${./src/abc/tools/json.clj}
            test -f ${./src/abc/tools/schema.clj}
            test -f ${./src/abc/tools/aozora_csv.clj}
            test -f ${./src/abc/tools/aozora_history_audit.clj}
            test -f ${./src/abc/tools/aozora_ingest.clj}
            test -f ${./src/abc/git.clj}
            test -f ${./prototypes/tei-eaj-comparison/tei_eaj_compare.py}
            test -f ${./prototypes/tei-eaj-comparison/test_tei_eaj_compare.py}
            test -f ${./src/abc/tools/manifest_index.clj}
            test -f ${./src/abc/tools/logging.clj}
            test -f ${./src/abc/tools/manifest_to_rdf.clj}
            test -f ${./src/abc/tools/materialize_publication.clj}
            test -f ${./src/abc/tools/metadata_record.clj}
            test -f ${./src/abc/tools/parser_ir_plaintext.clj}
            test -f ${./src/abc/tools/parser_ir_publication_policy.clj}
            test -f ${./src/abc/tools/parser_ir_tei.clj}
            test -f ${./src/abc/tools/parser_ir_vocabulary.clj}
            test -f ${./src/abc/tools/person_drift_history.clj}
            test -f ${./src/abc/tools/person_record.clj}
            test -f ${./src/abc/tools/rdf_prefixes.clj}
            test -f ${./src/abc/tools/schematron.clj}
            test -f ${./src/abc/tools/shacl.clj}
            test -f ${./src/abc/tools/tei.clj}
            test -f ${./src/abc/tools/tei_header.clj}
            test -f ${./src/abc/tools/validate_design_bundle.clj}
            test -f ${./schemas/metadata-record.schema.json}
            test -f ${./schemas/person-record.schema.json}
            test -f ${./schemas/tei-profile.rng}
            test -f ${./schemas/tei-profile.sch}
            test -f ${./schemas/tei-validation-result.schema.json}
            test -f ${./test/abc/tools/hash_test.clj}
            test -f ${./test/abc/tools/jcs_test.clj}
            test -f ${./test/abc/tools/schema_test.clj}
            test -f ${./test/abc/tools/manifest_index_test.clj}
            test -f ${./test/abc/tools/manifest_to_rdf_test.clj}
            test -f ${./test/abc/tools/materialize_import_test.clj}
            test -f ${./test/abc/tools/materialize_publication_test.clj}
            test -f ${./test/abc/tools/parser_ir_plaintext_test.clj}
            test -f ${./test/abc/tools/parser_ir_publication_policy_test.clj}
            test -f ${./test/abc/tools/parser_ir_tei_test.clj}
            test -f ${./test/abc/tools/parser_ir_vocabulary_test.clj}
            test -f ${./test/abc/tools/aozora_csv_test.clj}
            test -f ${./test/abc/tools/aozora_history_audit_test.clj}
            test -f ${./test/abc/git_blob_test.clj}
            test -f ${./test/abc/tools/metadata_record_test.clj}
            test -f ${./test/abc/tools/person_drift_history_test.clj}
            test -f ${./test/abc/tools/person_record_test.clj}
            test -f ${./test/abc/tools/aozora_ingest_test.clj}
            test -f ${./test/abc/tools/schematron_test.clj}
            test -f ${./test/abc/tools/shacl_test.clj}
            test -f ${./test/abc/tools/tei_test.clj}
            test -f ${./test/abc/tools/tei_header_test.clj}
            test -f ${./test/abc/tools/tei_header_unit_test.clj}
            test -f ${./examples/v0/example-work/metadata-record.json}
            test -f ${./examples/v0/example-work/metadata-record.ttl}
            test -f ${./examples/v0/example-persons/000879.json}
            test -f ${./data/parser-ir-publication-policy-v0.json}
            test -f ${./test/abc/tools/validate_design_bundle_test.clj}
            test -f ${./test/abc/annotation_schema_test.clj}
            test -f ${./test/abc/text_test.clj}
            test -f ${./test/abc/ndc_test.clj}
            mkdir -p "$out"
            echo "ABC v0 contract source surface is present." > "$out/result.txt"
          '';

          tei-profile-drift = pkgs.runCommand "abc-tei-profile-drift" { } ''
            # ADR 0012: schemas/tei-profile.odd is canonical; the .rng and
            # .sch are reproducibly generated artifacts. This check
            # regenerates them from the ODD via TEI Stylesheets, applies
            # the same build-artifact canonicalization (timestamp strip +
            # ABC pattern-id rewrite), and byte-diffs against the
            # checked-in files. Any drift fails the build so the ODD
            # remains the single source of truth.
            diff -u ${./schemas/tei-profile.rng} ${tei-profile-artifacts}/tei-profile.rng
            diff -u ${./schemas/tei-profile.sch} ${tei-profile-artifacts}/tei-profile.sch
            mkdir -p "$out"
            echo "schemas/tei-profile.{rng,sch} match the ODD-derived artifacts." > "$out/result.txt"
          '';

          tei-eaj-aozora-comparison-source = pkgs.runCommand "abc-tei-eaj-aozora-comparison-source" { } ''
            test -f ${tei-eaj-aozora-tei}/README.md
            test -f ${tei-eaj-aozora-tei}/data/complete/tei_lib_lv4/1567_tei.xml
            test -f ${tei-eaj-aozora-tei}/data/complete/tei_lib_lv4/1567_header_updated.xml
            grep -q "走れメロス" ${tei-eaj-aozora-tei}/data/complete/tei_lib_lv4/1567_tei.xml
            grep -q "Best Practice for TEI in Libraries" ${tei-eaj-aozora-tei}/README.md
            mkdir -p "$out"
            echo "Pinned TEI-EAJ/aozora_tei comparison source includes the Melos Level 4 fixtures." > "$out/result.txt"
          '';

          tei-eaj-comparison-probe-tests =
            pkgs.runCommand "abc-tei-eaj-comparison-probe-tests" { nativeBuildInputs = [ pkgs.python3 ]; }
              ''
                cp -R ${./prototypes/tei-eaj-comparison} probe
                chmod -R u+w probe
                python3 -m unittest discover -s probe -p 'test_*.py'
                mkdir -p "$out"
                echo "TEI-EAJ comparison probe tests passed." > "$out/result.txt"
              '';

          tei-eaj-aozora-report-generation =
            pkgs.runCommand "abc-tei-eaj-aozora-report-generation" { nativeBuildInputs = [ pkgs.python3 ]; }
              ''
                set -euo pipefail
                mkdir -p abc
                cat > abc/melos.xml <<'XML'
                <?xml version="1.0" encoding="UTF-8"?>
                <TEI xmlns="http://www.tei-c.org/ns/1.0">
                  <teiHeader>
                    <fileDesc>
                      <titleStmt><title>走れメロス</title></titleStmt>
                      <publicationStmt><idno type="aozora-work-id">001567</idno></publicationStmt>
                      <sourceDesc><p>source</p></sourceDesc>
                    </fileDesc>
                  </teiHeader>
                  <text><body><p>メロス</p></body></text>
                </TEI>
                XML
                python3 ${./prototypes/tei-eaj-comparison/tei_eaj_compare.py} \
                  --report melos \
                  --abc abc/melos.xml \
                  --tei-eaj-root ${tei-eaj-aozora-tei} \
                  --source-rev 77a675fc2771936f9544505d922d4cd45075338c \
                  --output melos.md
                python3 ${./prototypes/tei-eaj-comparison/tei_eaj_compare.py} \
                  --report all-work \
                  --abc-tei 1567=abc/melos.xml \
                  --tei-eaj-root ${tei-eaj-aozora-tei} \
                  --source-rev 77a675fc2771936f9544505d922d4cd45075338c \
                  --output all-work.md
                grep -q "TEI-EAJ Melos files found: 2" melos.md
                grep -q "TEI-EAJ XML files scanned: 62" all-work.md
                grep -q "Compared TEI-EAJ files: 2" all-work.md
                grep -q "Missing ABC counterparts: 55" all-work.md
                grep -q "TEI-EAJ files without candidate work IDs: 5" all-work.md
                mkdir -p "$out"
                cp melos.md all-work.md "$out"/
                echo "TEI-EAJ comparison reports regenerate against the pinned source." > "$out/result.txt"
              '';

          adr-acceptance-criteria = pkgs.runCommand "abc-adr-acceptance-criteria" { } ''
            cp -R ${./.} source
            chmod -R u+w source
            cd source
            bash nix/check-acceptance-criteria.sh
            mkdir -p "$out"
            echo "ADR acceptance-criteria lint passed (ratcheted)." > "$out/result.txt"
          '';
          focused-test-coverage =
            pkgs.runCommand "abc-focused-test-coverage" { nativeBuildInputs = [ pkgs.python3 ]; }
              ''
                cp -R ${./.} source
                chmod -R u+w source
                cd source
                bash nix/check-focused-test-coverage.sh
                mkdir -p "$out"
                echo "focused-test allowlist covers all *_test.clj (ratcheted)." > "$out/result.txt"
              '';
          swi-prolog-smoke =
            pkgs.runCommand "abc-swi-prolog-smoke" { nativeBuildInputs = [ pkgs.swi-prolog ]; }
              ''
                # SWI-Prolog is the pinned CI dialect for Layer C (design spec §7.5).
                # chiasmus_verify prolog is exploratory/manual only; this pin makes
                # the dialect (negation, tabling, module syntax, CLI, repro) a build input.
                cat > "$TMPDIR/smoke.pl" <<'PL'
                :- initialization(main).
                main :- write('swipl ok'), nl, halt.
                PL
                swipl --quiet -t main -f "$TMPDIR/smoke.pl" > "$out"
              '';
          prolog-cross-artifact =
            pkgs.runCommand "abc-prolog-cross-artifact" { nativeBuildInputs = [ pkgs.swi-prolog ]; }
              ''
                set -euo pipefail
                cp -R ${./.} source
                chmod -R u+w source
                cd source
                # Reads COMMITTED fact files (regenerated & byte-checked by the
                # clj-nix-focused-tests derivation via the emitter). swipl only —
                # the Clojure byte-compare lives in clj-nix-focused-tests, which
                # has the offline cljDepsCache + deps.edn replacement setup. A plain
                # `clojure -e` here would fail the Nix sandbox's offline classpath.
                # Invocation: -g "(Goal -> halt(0) ; halt(1))" -t halt -s FILE...
                # halt/1 takes an integer, not a goal (the "halt(\+ Goal)" form
                # is a type error); -s (script-load) the fact + query files so the
                # predicates are visible to the goal.
                swipl -q -g "(\\+ violating_dup_identity(_) -> halt(0) ; halt(1))" -t halt \
                      -s fixtures/v0/facts/prolog/manifest_identity.pl \
                      -s docs/adr/manifest-identity-emitter-sanity.pl
                swipl -q -g "(\\+ dangling_person(_) -> halt(0) ; halt(1))" -t halt \
                      -s fixtures/v0/facts/prolog/person_records.pl \
                      -s fixtures/v0/facts/prolog/drift.pl \
                      -s docs/adr/person-id-referential-integrity.pl
                mkdir -p "$out"
                echo "Prolog cross-artifact gates hold: emitter sanity + person-id referential integrity (SWI-Prolog)." > "$out/result.txt"
              '';
        }
      );

      devShells = forAllSystems (
        system:
        let
          pkgs = import nixpkgs {
            inherit system;
            overlays = [
              clj-nix.overlays.default
              localPkgsOverlay
            ];
          };

          mecab = pkgs.mecab.overrideAttrs (oldAttrs: {
            postInstall = (oldAttrs.postInstall or "") + ''
              rm -f $out/lib/mecab/dic/unidi-cwj $out/lib/mecab/dic/unidic-cwj
              ln -s ${pkgs.unidic-cwj}/share/mecab/dic/unidic-cwj $out/lib/mecab/dic/unidic-cwj
            '';
          });
          unidic = pkgs.unidic-cwj;
          mecabDicDir = "${unidic}/share/mecab/dic/unidic-cwj";
        in
        {
          default = pkgs.mkShell {
            packages = with pkgs; [
              clojure
              git
              git-cliff
              jdk21
              jq
              mecab
              unidic
              libxml2
            ];

            LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [
              mecab
              pkgs.systemd
            ];

            MECABRC = "${mecab}/etc/mecabrc";
            MECAB_DICDIR = mecabDicDir;

            shellHook = ''
              export LD_LIBRARY_PATH="${
                pkgs.lib.makeLibraryPath [
                  mecab
                  pkgs.systemd
                ]
              }:''${LD_LIBRARY_PATH:-}"
              export MECABRC="${mecab}/etc/mecabrc"
              export MECAB_DICDIR="${mecabDicDir}"
            '';
          };

          validation = pkgs.mkShell {
            packages = [
              pkgs.git
              pkgs.git-cliff
              pkgs.jq
              pkgs.libxml2
            ];
          };
        }
      );
    };
}
