{
  description = "Aozora Bunko Converter development environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    local-pkgs = {
      url = "path:/home/bor/Projects/nix/pkgs";
      flake = false;
    };
    clj-nix = {
      url = "github:jlesquembre/clj-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    crane = {
      url = "github:ipetkov/crane/v0.23.4";
    };
  };

  outputs =
    {
      nixpkgs,
      local-pkgs,
      clj-nix,
      crane,
      ...
    }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];

      forAllSystems = nixpkgs.lib.genAttrs systems;
      localPkgsOverlay =
        final: _prev:
        import local-pkgs {
          pkgs = final;
          craneLib = crane.mkLib final;
        };
    in
    {
      formatter = forAllSystems (
        system:
        let
          pkgs = import nixpkgs { inherit system; };
        in
        pkgs.nixfmt
      );

      apps = forAllSystems (
        system:
        let
          pkgs = import nixpkgs {
            inherit system;
            overlays = [
              clj-nix.overlays.default
              localPkgsOverlay
            ];
          };
          tei-schema = pkgs.fetchurl {
            url = "https://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng";
            hash = "sha256-7MSfAMN/SQtd9xa2cuPbpjXrHknM2I+5aYWUmN9CwIQ=";
          };
          tei-stylesheets = pkgs.fetchzip {
            url = "https://github.com/TEIC/Stylesheets/releases/download/v7.60.0/tei-xsl-7.60.0.zip";
            hash = "sha256-KcDZmMNtJHFbaBlTgr37Yy6O6J/QLDcoAG20CmBDpKk=";
            stripRoot = false;
          };
          tei-p5subset = pkgs.fetchurl {
            url = "https://www.tei-c.org/Vault/P5/4.11.0/xml/tei/odd/p5subset.xml";
            hash = "sha256-r9HruHPKcY1hvly09hFkoRA3/gybYSomI+avGvGe8wE=";
          };
          tei-profile-artifacts =
            pkgs.runCommand "abc-tei-profile-artifacts"
              {
                nativeBuildInputs = [
                  pkgs.saxon-he
                  pkgs.gnused
                ];
              }
              ''
                set -euo pipefail
                cp ${./schemas/tei-profile.odd} tei-profile.odd
                saxon-he -s:tei-profile.odd \
                  -xsl:${tei-stylesheets}/xml/tei/stylesheet/odds/odd2odd.xsl \
                  -o:expanded.odd \
                  defaultSource=${tei-p5subset}
                saxon-he -s:expanded.odd \
                  -xsl:${tei-stylesheets}/xml/tei/stylesheet/odds/odd2relax.xsl \
                  -o:tei-profile.rng
                saxon-he -s:expanded.odd \
                  -xsl:${tei-stylesheets}/xml/tei/stylesheet/odds/extract-isosch.xsl \
                  -o:tei-profile.sch \
                  lang=en
                # Build-artifact canonicalization (ADR 0012). Two narrow
                # rewrites; the ODD remains source of truth.
                # 1. Strip non-deterministic generation timestamps so
                #    rebuilds are byte-stable.
                # 2. Rewrite ABC pattern IDs from
                #    `schematron-constraint-<ident>-<seq>` back to the
                #    `<ident>` the ODD's constraintSpec/@ident declared.
                #    Inherited TEI built-in pattern IDs are left untouched.
                sed -E -i 's|Schema generated from ODD source [0-9TZ:.+-]+\. \. ?|Schema generated from ODD source. |' tei-profile.rng
                sed -E -i "s|<!-- This file generated [0-9TZ:.+-]+ by 'extract-isosch.xsl'. -->|<!-- This file generated by 'extract-isosch.xsl'. -->|" tei-profile.sch
                sed -E -i 's|id="schematron-constraint-(abc-[a-z0-9-]+)-[0-9]+"|id="\1"|g' tei-profile.sch
                # Drop inherited TEI built-in patterns that the ODD did not
                # declare. The ABC v0 Schematron evaluator (abc.tools.schematron)
                # is a minimal subset and does not implement sch:let or other
                # features used by the inherited TEI corpus. The 7 ABC
                # constraintSpec rules are the committed contract surface.
                awk '
                  /^   <pattern id="schematron-constraint-/ { drop = 1 }
                  !drop { print }
                  drop && /^   <\/pattern>/ { drop = 0 }
                ' tei-profile.sch > tei-profile.sch.filtered
                mv tei-profile.sch.filtered tei-profile.sch
                mkdir -p "$out"
                cp tei-profile.rng tei-profile.sch "$out/"
              '';
        in
        {
          validate-design-bundle = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-validate-design-bundle" ''
                export PATH="${
                  pkgs.lib.makeBinPath [
                    pkgs.git-cliff
                    pkgs.libxml2
                  ]
                }:''${PATH:-}"
                export TEI_SCHEMA_PATH="${tei-schema}"
                exec ${pkgs.clojure}/bin/clojure -M:abc/validate-design-bundle "$@"
              ''
            );
            meta.description = "Validate ABC v0 design-bundle schemas and fixtures";
          };

          materialize-import = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-materialize-import" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/materialize-import "$@"
              ''
            );
            meta.description = "Materialize imported ab-validator output as ABC manifests";
          };

          materialize-publication = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-materialize-publication" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/materialize-publication "$@"
              ''
            );
            meta.description = "Materialize parser-IR publication plaintext and TEI artifacts";
          };

          manifest-to-rdf = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-manifest-to-rdf" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/manifest-to-rdf "$@"
              ''
            );
            meta.description = "Generate deterministic RDF/Turtle view from an ABC manifest";
          };

          aozora-ingest = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-aozora-ingest" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/aozora-ingest "$@"
              ''
            );
            meta.description = "Build a metadata-record JSON from an Aozora list_person_all_extended ZIP slice";
          };

          validate-corpus = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-validate-corpus" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/validate-corpus "$@"
              ''
            );
            meta.description = "Validate an ingested corpus directory through SHACL";
          };

          person-drift-history = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-person-drift-history" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/person-drift-history "$@"
              ''
            );
            meta.description = "Audit generated corpus snapshots for conservative person split/merge candidates";
          };

          aozora-history-audit = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-aozora-history-audit" ''
                exec ${pkgs.clojure}/bin/clojure -M:abc/aozora-history-audit "$@"
              ''
            );
            meta.description = "Extract two Aozora git refs, ingest them, validate current corpus, and report person drift candidates";
          };

          aozora-upstream-audit = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-aozora-upstream-audit" ''
                set -euo pipefail
                if [ ! -d examples/v0/example-persons ]; then
                  echo "aozora-upstream-audit: run from the ABC repository root; examples/v0/example-persons not found" >&2
                  exit 2
                fi
                exec ${pkgs.clojure}/bin/clojure -M:abc/aozora-history-audit \
                  --drift-persons-dir examples/v0/example-persons \
                  --fail-on-candidates \
                  --fail-on-drift-participant-updates \
                  "$@"
              ''
            );
            meta.description = "Default after-upstream Aozora audit with drift sidecars and failure gates enabled";
          };

          regenerate-tei-profile = {
            type = "app";
            program = toString (
              pkgs.writeShellScript "abc-regenerate-tei-profile" ''
                set -euo pipefail
                target="''${1:-$PWD}"
                if [ ! -d "$target/schemas" ]; then
                  echo "regenerate-tei-profile: $target/schemas not found" >&2
                  echo "usage: nix run .#regenerate-tei-profile [-- <repo-root>]" >&2
                  exit 2
                fi
                install -m 0644 "${tei-profile-artifacts}/tei-profile.rng" "$target/schemas/tei-profile.rng"
                install -m 0644 "${tei-profile-artifacts}/tei-profile.sch" "$target/schemas/tei-profile.sch"
                echo "Updated $target/schemas/tei-profile.{rng,sch} from schemas/tei-profile.odd."
              ''
            );
            meta.description = "Regenerate schemas/tei-profile.{rng,sch} from schemas/tei-profile.odd via TEI Stylesheets";
          };
        }
      );

      checks = forAllSystems (
        system:
        let
          pkgs = import nixpkgs {
            inherit system;
            overlays = [
              clj-nix.overlays.default
              localPkgsOverlay
            ];
          };
          cljDepsCache = pkgs.mk-deps-cache {
            lockfile = ./deps-lock.json;
          };
          tei-stylesheets = pkgs.fetchzip {
            url = "https://github.com/TEIC/Stylesheets/releases/download/v7.60.0/tei-xsl-7.60.0.zip";
            hash = "sha256-KcDZmMNtJHFbaBlTgr37Yy6O6J/QLDcoAG20CmBDpKk=";
            stripRoot = false;
          };
          tei-p5subset = pkgs.fetchurl {
            url = "https://www.tei-c.org/Vault/P5/4.11.0/xml/tei/odd/p5subset.xml";
            hash = "sha256-r9HruHPKcY1hvly09hFkoRA3/gybYSomI+avGvGe8wE=";
          };
          tei-profile-artifacts =
            pkgs.runCommand "abc-tei-profile-artifacts"
              {
                nativeBuildInputs = [
                  pkgs.saxon-he
                  pkgs.gnused
                ];
              }
              ''
                set -euo pipefail
                cp ${./schemas/tei-profile.odd} tei-profile.odd
                saxon-he -s:tei-profile.odd \
                  -xsl:${tei-stylesheets}/xml/tei/stylesheet/odds/odd2odd.xsl \
                  -o:expanded.odd \
                  defaultSource=${tei-p5subset}
                saxon-he -s:expanded.odd \
                  -xsl:${tei-stylesheets}/xml/tei/stylesheet/odds/odd2relax.xsl \
                  -o:tei-profile.rng
                saxon-he -s:expanded.odd \
                  -xsl:${tei-stylesheets}/xml/tei/stylesheet/odds/extract-isosch.xsl \
                  -o:tei-profile.sch \
                  lang=en
                sed -E -i 's|Schema generated from ODD source [0-9TZ:.+-]+\. \. ?|Schema generated from ODD source. |' tei-profile.rng
                sed -E -i "s|<!-- This file generated [0-9TZ:.+-]+ by 'extract-isosch.xsl'. -->|<!-- This file generated by 'extract-isosch.xsl'. -->|" tei-profile.sch
                sed -E -i 's|id="schematron-constraint-(abc-[a-z0-9-]+)-[0-9]+"|id="\1"|g' tei-profile.sch
                # Drop inherited TEI built-in patterns that the ODD did not
                # declare. The ABC v0 Schematron evaluator (abc.tools.schematron)
                # is a minimal subset and does not implement sch:let or other
                # features used by the inherited TEI corpus. The 7 ABC
                # constraintSpec rules are the committed contract surface.
                awk '
                  /^   <pattern id="schematron-constraint-/ { drop = 1 }
                  !drop { print }
                  drop && /^   <\/pattern>/ { drop = 0 }
                ' tei-profile.sch > tei-profile.sch.filtered
                mv tei-profile.sch.filtered tei-profile.sch
                mkdir -p "$out"
                cp tei-profile.rng tei-profile.sch "$out/"
              '';
        in
        {
          clj-nix-focused-tests =
            pkgs.runCommand "abc-clj-nix-focused-tests"
              {
                nativeBuildInputs = [
                  pkgs.clojure
                  pkgs.git-cliff
                  pkgs.libxml2
                ];
              }
              ''
                cp -R ${./.} source
                chmod -R u+w source
                cd source
                cp ${./nix/clj-nix-deps.edn} deps.edn

                export HOME="${cljDepsCache}"
                export JAVA_TOOL_OPTIONS="-Duser.home=${cljDepsCache}"
                export CLJ_CONFIG="$HOME/.clojure"
                export CLJ_CACHE="$TMPDIR/cp-cache"
                export XDG_CONFIG_HOME="$TMPDIR/xdg-config"
                export GITLIBS="$HOME/.gitlibs"

                # The Nix sandbox has no network access; tests that need
                # the upstream TEI RelaxNG schema (fetched at app build
                # time, not at test time) skip cleanly when this flag is
                # set. End-to-end TEI validation runs via the
                # `nix run .#validate-design-bundle` app, not here.
                export ABC_TEI_SCHEMA_SKIP=1

                clojure -M:abc/focused-test

                mkdir -p "$out"
                echo "ABC focused Clojure tests passed with clj-nix dependency cache." > "$out/result.txt"
              '';

          aat-parser-ir-probe-tests =
            pkgs.runCommand "abc-aat-parser-ir-probe-tests"
              {
                nativeBuildInputs = [
                  pkgs.python3
                ];
              }
              ''
                cp -R ${./.} source
                chmod -R u+w source
                cd source

                python3 -m unittest prototypes/aat-to-parser-ir-probe/test_probe_mapping.py

                mkdir -p "$out"
                echo "AAT parser-IR probe tests passed." > "$out/result.txt"
              '';

          contract-surface = pkgs.runCommand "abc-contract-surface-check" { } ''
            test -f ${./resources/abc/ndc9.edn.xz}
            test -f ${./nix/clj-nix-deps.edn}
            test -f ${./deps-lock.json}
            test -f ${./src/abc/annotation/schema.clj}
            test -f ${./src/abc/text.clj}
            test -f ${./src/abc/ndc.clj}
            test -f ${./src/abc/tools/hash.clj}
            test -f ${./src/abc/tools/jcs.clj}
            test -f ${./src/abc/tools/json.clj}
            test -f ${./src/abc/tools/schema.clj}
            test -f ${./src/abc/tools/aozora_csv.clj}
            test -f ${./src/abc/tools/aozora_history_audit.clj}
            test -f ${./src/abc/tools/aozora_ingest.clj}
            test -f ${./src/abc/git.clj}
            test -f ${./src/abc/tools/manifest_index.clj}
            test -f ${./src/abc/tools/logging.clj}
            test -f ${./src/abc/tools/manifest_to_rdf.clj}
            test -f ${./src/abc/tools/materialize_publication.clj}
            test -f ${./src/abc/tools/metadata_record.clj}
            test -f ${./src/abc/tools/parser_ir_plaintext.clj}
            test -f ${./src/abc/tools/parser_ir_publication_policy.clj}
            test -f ${./src/abc/tools/parser_ir_tei.clj}
            test -f ${./src/abc/tools/parser_ir_vocabulary.clj}
            test -f ${./src/abc/tools/person_drift_history.clj}
            test -f ${./src/abc/tools/person_record.clj}
            test -f ${./src/abc/tools/rdf_prefixes.clj}
            test -f ${./src/abc/tools/schematron.clj}
            test -f ${./src/abc/tools/shacl.clj}
            test -f ${./src/abc/tools/tei.clj}
            test -f ${./src/abc/tools/tei_header.clj}
            test -f ${./src/abc/tools/validate_design_bundle.clj}
            test -f ${./schemas/metadata-record.schema.json}
            test -f ${./schemas/person-record.schema.json}
            test -f ${./schemas/tei-profile.rng}
            test -f ${./schemas/tei-profile.sch}
            test -f ${./schemas/tei-validation-result.schema.json}
            test -f ${./test/abc/tools/hash_test.clj}
            test -f ${./test/abc/tools/jcs_test.clj}
            test -f ${./test/abc/tools/schema_test.clj}
            test -f ${./test/abc/tools/manifest_index_test.clj}
            test -f ${./test/abc/tools/manifest_to_rdf_test.clj}
            test -f ${./test/abc/tools/materialize_import_test.clj}
            test -f ${./test/abc/tools/materialize_publication_test.clj}
            test -f ${./test/abc/tools/parser_ir_plaintext_test.clj}
            test -f ${./test/abc/tools/parser_ir_publication_policy_test.clj}
            test -f ${./test/abc/tools/parser_ir_tei_test.clj}
            test -f ${./test/abc/tools/parser_ir_vocabulary_test.clj}
            test -f ${./test/abc/tools/aozora_csv_test.clj}
            test -f ${./test/abc/tools/aozora_history_audit_test.clj}
            test -f ${./test/abc/git_blob_test.clj}
            test -f ${./test/abc/tools/metadata_record_test.clj}
            test -f ${./test/abc/tools/person_drift_history_test.clj}
            test -f ${./test/abc/tools/person_record_test.clj}
            test -f ${./test/abc/tools/aozora_ingest_test.clj}
            test -f ${./test/abc/tools/schematron_test.clj}
            test -f ${./test/abc/tools/shacl_test.clj}
            test -f ${./test/abc/tools/tei_test.clj}
            test -f ${./test/abc/tools/tei_header_test.clj}
            test -f ${./test/abc/tools/tei_header_unit_test.clj}
            test -f ${./examples/v0/example-work/metadata-record.json}
            test -f ${./examples/v0/example-work/metadata-record.ttl}
            test -f ${./examples/v0/example-persons/000879.json}
            test -f ${./data/parser-ir-publication-policy-v0.json}
            test -f ${./test/abc/tools/validate_design_bundle_test.clj}
            test -f ${./test/abc/annotation_schema_test.clj}
            test -f ${./test/abc/text_test.clj}
            test -f ${./test/abc/ndc_test.clj}
            mkdir -p "$out"
            echo "ABC v0 contract source surface is present." > "$out/result.txt"
          '';

          tei-profile-drift = pkgs.runCommand "abc-tei-profile-drift" { } ''
            # ADR 0012: schemas/tei-profile.odd is canonical; the .rng and
            # .sch are reproducibly generated artifacts. This check
            # regenerates them from the ODD via TEI Stylesheets, applies
            # the same build-artifact canonicalization (timestamp strip +
            # ABC pattern-id rewrite), and byte-diffs against the
            # checked-in files. Any drift fails the build so the ODD
            # remains the single source of truth.
            diff -u ${./schemas/tei-profile.rng} ${tei-profile-artifacts}/tei-profile.rng
            diff -u ${./schemas/tei-profile.sch} ${tei-profile-artifacts}/tei-profile.sch
            mkdir -p "$out"
            echo "schemas/tei-profile.{rng,sch} match the ODD-derived artifacts." > "$out/result.txt"
          '';

          adr0001-invariants =
            pkgs.runCommand "abc-adr0001-invariants" { nativeBuildInputs = [ pkgs.z3 ]; }
              ''
                # ADR 0001: verify the manifest-identity invariants with Z3.
                # Each .smt2 file is a counterexample-seeking query; Z3 must
                # report `unsat` (no counterexample exists) for the invariant
                # to hold. Runs offline so it works in the Nix sandbox / CI.
                # See docs/adr/0001-invariants.README.md for the rationale and
                # the list of invariants (R1 reproducibility-conflict,
                # R2 non-circularity; R3 null-dimension is covered by the
                # canonicalization fixture, not a solver).
                for spec in ${./docs/adr/r1-reproducibility-conflict.smt2} ${./docs/adr/r2-non-circularity.smt2}; do
                  result="$(z3 "$spec")"
                  case "$result" in
                    unsat) ;;
                    *)
                      echo "ADR 0001 invariant check FAILED for $spec:" >&2
                      echo "$result" >&2
                      exit 1
                      ;;
                  esac
                done
                mkdir -p "$out"
                echo "ADR 0001 manifest-identity invariants verified (Z3 reports unsat for both counterexample queries)." > "$out/result.txt"
              '';

          adr0020-drift-cardinality =
            pkgs.runCommand "abc-adr0020-drift-cardinality" { nativeBuildInputs = [ pkgs.z3 ]; }
              ''
                # ADR 0020: verify the person-identity drift event cardinality
                # invariants with Z3. Counterexample-seeking query; Z3 must
                # report `unsat`. Offline / Nix-sandbox-safe.
                # ADR 0020 lines 148-149:
                #   - a split has exactly 1 predecessor and >= 2 successors
                #   - a merge has >= 2 predecessors and exactly 1 successor
                # See docs/adr/r3-drift-cardinality.smt2 for the formal spec.
                result="$(z3 ${./docs/adr/r3-drift-cardinality.smt2})"
                case "$result" in
                  unsat) ;;
                  *)
                    echo "ADR 0020 drift cardinality check FAILED:" >&2
                    echo "$result" >&2
                    exit 1
                    ;;
                esac
                mkdir -p "$out"
                echo "ADR 0020 drift-event cardinality invariants verified (Z3 reports unsat)." > "$out/result.txt"
              '';

          # Mutation-vacuity guardrail. For each committed invariant .smt2,
          # strip the `; BEGIN-INVARIANTS ... ; END-INVARIANTS` block (the
          # stipulated invariant P) and require Z3 to report `sat` on the
          # remainder (axioms + counterexample ¬P). If the stripped fragment
          # is still `unsat`, the counterexample is unreachable for reasons
          # orthogonal to P — the original `unsat` was vacuous (P did no work).
          #
          # Scope (stated honestly): this catches mode-A vacuity
          # (self-refuting / axiom-refuted counterexamples) only. It does NOT
          # catch mode-B vacuity (invariant stipulated as P ∧ ¬P tautology),
          # which is the actual defect of the current R1/R2/R3 files — all
          # three pass this check. Mode-B requires binding P to the real
          # schema/code; see
          # docs/handoffs/formal-verification-assessment-critique.md §5–§7.
          adr-invariants-vacuity =
            pkgs.runCommand "abc-adr-invariants-vacuity" { nativeBuildInputs = [ pkgs.z3 ]; }
              ''
                set -euo pipefail
                for spec in ${./docs/adr/r1-reproducibility-conflict.smt2} ${./docs/adr/r2-non-circularity.smt2} ${./docs/adr/r3-drift-cardinality.smt2}; do
                  if ! grep -q '; BEGIN-INVARIANTS' "$spec" || ! grep -q '; END-INVARIANTS' "$spec"; then
                    echo "adr-invariants-vacuity: $spec is missing ; BEGIN/END-INVARIANTS delimiters." >&2
                    echo "Every invariant assertion must be inside a delimited block so this" >&2
                    echo "check can strip it. See formal-verification-assessment-critique.md §6." >&2
                    exit 1
                  fi
                  stripped="$(sed '/; BEGIN-INVARIANTS/,/; END-INVARIANTS/d' "$spec")"
                  if ! printf '%s\n' "$stripped" | grep -q '(check-sat)'; then
                    echo "adr-invariants-vacuity: $spec has no (check-sat) after stripping the invariant block." >&2
                    exit 1
                  fi
                  result="$(printf '%s\n' "$stripped" | z3 -in)"
                  case "$result" in
                    sat) ;;
                    *)
                      echo "adr-invariants-vacuity FAILED for $spec:" >&2
                      echo "  After stripping the invariant block, Z3 reported '$result' (expected sat)." >&2
                      echo "  The counterexample is unreachable without the invariant — the original" >&2
                      echo "  unsat did not depend on P. See formal-verification-assessment-critique.md §5." >&2
                      exit 1
                      ;;
                  esac
                done
                mkdir -p "$out"
                echo "ADR invariant vacuity guardrail passed: each counterexample is reachable when P is stripped (mode-A)." > "$out/result.txt"
              '';
          adr-acceptance-criteria = pkgs.runCommand "abc-adr-acceptance-criteria" { } ''
            cp -R ${./.} source
            chmod -R u+w source
            cd source
            bash nix/check-acceptance-criteria.sh
            mkdir -p "$out"
            echo "ADR acceptance-criteria lint passed (ratcheted)." > "$out/result.txt"
          '';
          swi-prolog-smoke =
            pkgs.runCommand "abc-swi-prolog-smoke" { nativeBuildInputs = [ pkgs.swi-prolog ]; }
              ''
                # SWI-Prolog is the pinned CI dialect for Layer C (design spec §7.5).
                # chiasmus_verify prolog is exploratory/manual only; this pin makes
                # the dialect (negation, tabling, module syntax, CLI, repro) a build input.
                cat > "$TMPDIR/smoke.pl" <<'PL'
                :- initialization(main).
                main :- write('swipl ok'), nl, halt.
                PL
                swipl --quiet -t main -f "$TMPDIR/smoke.pl" > "$out"
              '';
          prolog-cross-artifact =
            pkgs.runCommand "abc-prolog-cross-artifact" { nativeBuildInputs = [ pkgs.swi-prolog ]; }
              ''
                set -euo pipefail
                cp -R ${./.} source
                chmod -R u+w source
                cd source
                # Reads COMMITTED fact files (regenerated & byte-checked by the
                # clj-nix-focused-tests derivation via the emitter). swipl only —
                # the Clojure byte-compare lives in clj-nix-focused-tests, which
                # has the offline cljDepsCache + deps.edn replacement setup. A plain
                # `clojure -e` here would fail the Nix sandbox's offline classpath.
                # Invocation: -g "(Goal -> halt(0) ; halt(1))" -t halt -s FILE...
                # halt/1 takes an integer, not a goal (the "halt(\+ Goal)" form
                # is a type error); -s (script-load) the fact + query files so the
                # predicates are visible to the goal.
                swipl -q -g "(\\+ violating_dup_identity(_) -> halt(0) ; halt(1))" -t halt \
                      -s fixtures/v0/facts/prolog/manifest_identity.pl \
                      -s docs/adr/manifest-identity-emitter-sanity.pl
                swipl -q -g "(\\+ dangling_person(_) -> halt(0) ; halt(1))" -t halt \
                      -s fixtures/v0/facts/prolog/person_records.pl \
                      -s fixtures/v0/facts/prolog/drift.pl \
                      -s docs/adr/person-id-referential-integrity.pl
                mkdir -p "$out"
                echo "Prolog cross-artifact gates hold: emitter sanity + person-id referential integrity (SWI-Prolog)." > "$out/result.txt"
              '';
        }
      );

      devShells = forAllSystems (
        system:
        let
          pkgs = import nixpkgs {
            inherit system;
            overlays = [
              clj-nix.overlays.default
              localPkgsOverlay
            ];
          };

          mecab = pkgs.mecab.overrideAttrs (oldAttrs: {
            postInstall = (oldAttrs.postInstall or "") + ''
              rm -f $out/lib/mecab/dic/unidi-cwj $out/lib/mecab/dic/unidic-cwj
              ln -s ${pkgs.unidic-cwj}/share/mecab/dic/unidic-cwj $out/lib/mecab/dic/unidic-cwj
            '';
          });
          unidic = pkgs.unidic-cwj;
          mecabDicDir = "${unidic}/share/mecab/dic/unidic-cwj";
        in
        {
          default = pkgs.mkShell {
            packages = with pkgs; [
              clojure
              git
              git-cliff
              jdk21
              jq
              mecab
              unidic
              libxml2
            ];

            LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [
              mecab
              pkgs.systemd
            ];

            MECABRC = "${mecab}/etc/mecabrc";
            MECAB_DICDIR = mecabDicDir;

            shellHook = ''
              export LD_LIBRARY_PATH="${
                pkgs.lib.makeLibraryPath [
                  mecab
                  pkgs.systemd
                ]
              }:''${LD_LIBRARY_PATH:-}"
              export MECABRC="${mecab}/etc/mecabrc"
              export MECAB_DICDIR="${mecabDicDir}"
            '';
          };

          validation = pkgs.mkShell {
            packages = [
              pkgs.git
              pkgs.git-cliff
              pkgs.jq
              pkgs.libxml2
            ];
          };
        }
      );
    };
}
