(ns abc.tools.diagram.core-test
  (:require [clojure.test :refer [deftest is]]
            [clojure.string :as str]
            [abc.tools.diagram.core :as core]))

(def sample
  {:id :t :out-path "/tmp/abc-diagram-core-test.mmd" :regen "regen-cmd"
   :build (fn [] {:direction "TD"
                  :nodes [{:id :a :label "A"}]
                  :edges [] :class-defs {}})
   :lint (fn [] [])})

(deftest render-prepends-generated-header
  (let [out (core/render sample)]
    (is (str/starts-with? out "%% GENERATED by regen-cmd"))
    (is (str/includes? out "flowchart TD"))))

(deftest run-writes-then-check-passes
  (is (:ok? (core/run! [sample] {:check? false})))     ;; writes the file
  (let [r (core/run! [sample] {:check? true})]         ;; now current
    (is (:ok? r))
    (is (= [] (:drifts r)))))

(deftest run-reports-lint-problems-without-exiting
  (let [bad (assoc sample :lint (fn [] ["boom"]))
        r (core/run! [bad] {:check? true})]
    (is (false? (:ok? r)))
    (is (= ["boom"] (:problems r)))))
