(ns abc.tools.diagram.core-test
  (:require [clojure.test :refer [deftest is]]
            [clojure.string :as str]
            [abc.tools.diagram.core :as core]))

(defn sample [out-path]
  {:id :t :out-path out-path :regen "regen-cmd"
   :build (fn [] {:direction "TD"
                  :nodes [{:id :a :label "A"}]
                  :edges [] :class-defs {}})
   :lint (fn [] [])})

(deftest render-prepends-generated-header
  (let [out (core/render (sample "unused-by-render"))]
    (is (str/starts-with? out "%% GENERATED by regen-cmd"))
    (is (str/includes? out "flowchart TD"))))

(deftest run-writes-then-check-passes
  (let [file (java.io.File/createTempFile "abc-diagram-core" ".mmd")
        diagram (sample (.getPath file))]
    (try
      (is (:ok? (core/run! [diagram] {:check? false})))
      (let [r (core/run! [diagram] {:check? true})]
        (is (:ok? r))
        (is (= [] (:drifts r))))
      (finally
        (java.nio.file.Files/deleteIfExists (.toPath file))))))

(deftest run-reports-lint-problems-without-exiting
  (let [bad (assoc (sample "unused-by-lint") :lint (fn [] ["boom"]))
        r (core/run! [bad] {:check? true})]
    (is (false? (:ok? r)))
    (is (= ["boom"] (:problems r)))))
