//! Runs with serde_json/preserve_order ACTIVE (this workspace enables it),
//! so `serde_json::Map` preserves insertion order and these tests are a
//! genuine probe of explicit sorting — in the root workspace (BTreeMap)
//! they would pass vacuously.
use std::path::{Path, PathBuf};

use serde_json::{json, Map, Value};

#[test]
fn sort_keys_deep_sorts_insertion_ordered_maps() {
    let mut inner = Map::new();
    inner.insert("zeta".into(), json!(1));
    inner.insert("alpha".into(), json!([{"b": 2, "a": 3}]));
    let mut outer = Map::new();
    outer.insert("meta".into(), Value::Object(inner));
    outer.insert("blocks".into(), json!([]));
    let sorted = ab_aat_to_parser_ir::sort_keys_deep(Value::Object(outer));
    let text = serde_json::to_string(&sorted).unwrap();
    assert_eq!(
        text,
        r#"{"blocks":[],"meta":{"alpha":[{"a":3,"b":2}],"zeta":1}}"#
    );
}

/// Golden generated by running the exact same `convert` + serialization
/// call in the ROOT workspace (default `serde_json`, `BTreeMap`-backed
/// `Map`, no `preserve_order`), via:
///
/// ```text
/// export RUSTC_WRAPPER= SCCACHE_DISABLE=1
/// cd ab-validator
/// cargo build -p ab-aat-to-parser-ir --bin ab-aat-to-parser-ir
/// ./target/debug/ab-aat-to-parser-ir convert \
///   --aat <this test's fixture written to a temp file> \
///   --mapping data/aat-to-parser-ir-mapping-v1.json \
///   --parser-ir-out /tmp/canary-parser-ir.json \
///   --divergence-out /tmp/canary-divergence.json \
///   --abc-root data/abc-schemas
/// ```
///
/// The fixture is the same minimal AAT document used by
/// `crates/ab-aat-to-parser-ir/tests/integration.rs`'s
/// `cli_convert_writes_parser_ir_and_divergence_bundle` test (single
/// paragraph, single "A" text run).
const EXPECTED_PARSER_IR: &str = r#"{
  "derived_from": {
    "aat_adapter": "fixture",
    "aat_adapter_version": "fixture 0.1.0",
    "aat_version": 1,
    "mapping_id": "https://w3id.org/abc/mappings/aat-v1-to-parser-ir-v1/generated-probe",
    "mapping_schema_hash": "sha256:e6af01115ccdb7c5cad086eee4c458230f6b6f55e0dfee7791730b48994283e2",
    "mapping_version": "0.2.8"
  },
  "errors": [],
  "nodes": [
    {
      "span": {
        "column": null,
        "coordinate_system": "decoded_utf8",
        "end": 1,
        "line": null,
        "start": 0
      },
      "text": "A",
      "type": "text"
    }
  ],
  "paragraphs": [
    {
      "classification": "direct",
      "id": "p000000",
      "node_range": {
        "end": 1,
        "start": 0
      },
      "role": "body",
      "source_pointer": "blocks[0]",
      "span": {
        "column": null,
        "coordinate_system": "decoded_utf8",
        "end": 1,
        "line": null,
        "start": 0
      },
      "span_source": "derived"
    }
  ],
  "schema_hash": "sha256:a1e1b5069fdec17cbb1f94eb5e9a582d1b109dd95c07257f4da7d9b76c82cfa2",
  "schema_id": "https://w3id.org/abc/schemas/parser-ir.schema.json",
  "sentence_segmentation": {
    "coordinate_system": "decoded_utf8",
    "coverage": "body-paragraphs",
    "schema_version": "sentence-segmentation-v1",
    "splitter_id": "ab-plaintext-japanese-v2"
  },
  "sentences": [
    {
      "id": "s000000",
      "node_range": {
        "end": 1,
        "start": 0
      },
      "orthographic_annotation_indices": [],
      "paragraph_id": "p000000",
      "span": {
        "coordinate_system": "decoded_utf8",
        "end": 1,
        "start": 0
      },
      "tags": []
    }
  ],
  "source": {
    "encoding": "UTF-8",
    "normalization": "source",
    "source_path": null,
    "work_content_hash": "sha256:6666666666666666666666666666666666666666666666666666666666666666"
  },
  "warnings": []
}"#;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn abc_root(repo: &Path) -> PathBuf {
    std::env::var_os("AB_ABC_ROOT")
        .map(PathBuf::from)
        .unwrap_or_else(|| repo.join("data/abc-schemas"))
}

#[test]
fn convert_and_serialize_parser_ir_is_canonical_under_preserve_order() {
    let repo = repo_root();
    let abc = abc_root(&repo);
    // The mapping loaded below (`aat-to-parser-ir-mapping-v1.json`) declares
    // `source_aat_version: 1`; `MappingDocument::preflight` requires the
    // loaded AAT schema version to match, so this canary — whose fixture AAT
    // document is itself `"version": 1` — loads the v1 schema tuple. (v2
    // fails preflight with "mapping/schema tuple mismatch".) This preserves
    // the canary's original assertion: preserve_order active, canonical
    // (sorted-key) parser-IR serialization is unaffected by map ordering.
    let schemas = ab_aat_to_parser_ir::SchemaSet::load_for_aat_version(&repo, &abc, 1).unwrap();
    let mapping = ab_aat_to_parser_ir::MappingDocument::from_path(
        &repo.join("data/aat-to-parser-ir-mapping-v1.json"),
    )
    .unwrap();

    let aat = json!({
        "version": 1,
        "work_id": "canary",
        "meta": {
            "adapter": "fixture",
            "adapter_version": "fixture 0.1.0",
            "source_encoding": "utf-8",
            "source_hash": "sha256:6666666666666666666666666666666666666666666666666666666666666666",
            "parse_complete": true,
            "warnings": []
        },
        "blocks": [{"kind": "paragraph", "content": [{"kind": "text", "value": "A"}]}]
    });

    let output = ab_aat_to_parser_ir::convert(ab_aat_to_parser_ir::ConversionRequest {
        aat,
        mapping,
        schemas,
        options: ab_aat_to_parser_ir::ConversionOptions::default(),
    })
    .unwrap();

    let text = ab_aat_to_parser_ir::to_canonical_json_pretty(output.parser_ir).unwrap();
    assert_eq!(text, EXPECTED_PARSER_IR);
}
