(ns abc.tools.linked-art-test
  (:require [abc.test-fs :as tfs]
            [abc.tools.files :as files]
            [abc.tools.hash :as hash]
            [abc.tools.jcs :as jcs]
            [abc.tools.linked-art :as la]
            [clojure.java.io :as io]
            [clojure.test :refer [deftest is testing]]))

(def manifest-path "examples/v0/example-work/manifest.json")
(def metadata-record-path "examples/v0/example-work/metadata-record.json")
(def context-path "contexts/abc-v0.jsonld")
(def candidate-path "examples/v0/example-work/lod/linked-art-candidate.jsonld")
(def expanded-path "examples/v0/example-work/lod/linked-art-expanded.normalized.json")
(def result-path "examples/v0/example-work/lod/jsonld-context-validation-result.json")

(defn- write-to-temp! [dir]
  (la/write-publication-view!
   {:manifest-path manifest-path
    :metadata-record-path metadata-record-path
    :context-path context-path
    :candidate-path (str (io/file dir "candidate.jsonld"))
    :expanded-path (str (io/file dir "expanded.json"))
    :result-path (str (io/file dir "result.json"))})
  dir)

(defn- file-bytes [^java.io.File f]
  (with-open [in (io/input-stream f)]
    (.readAllBytes in)))

(deftest committed-fixtures-match-harness-output-test
  (testing "the committed LOD fixtures are exactly what write-publication-view! emits"
    (tfs/with-temp-dir [dir]
      (write-to-temp! dir)
      (let [regen-candidate (file-bytes (io/file dir "candidate.jsonld"))
            regen-expanded (file-bytes (io/file dir "expanded.json"))
            regen-result (file-bytes (io/file dir "result.json"))
            on-disk-candidate (file-bytes (io/file candidate-path))
            on-disk-expanded (file-bytes (io/file expanded-path))
            on-disk-result (file-bytes (io/file result-path))]
        (is (= (seq on-disk-candidate) (seq regen-candidate))
            "linked-art-candidate.jsonld must equal the harness-regenerated bytes")
        (is (= (seq on-disk-expanded) (seq regen-expanded))
            "linked-art-expanded.normalized.json must equal the harness-regenerated bytes")
        (is (= (seq on-disk-result) (seq regen-result))
            "jsonld-context-validation-result.json must equal the harness-regenerated bytes")))))

(deftest determinism-test
  (testing "running the harness twice produces byte-identical output"
    (tfs/with-temp-dir [dir-a]
      (tfs/with-temp-dir [dir-b]
        (write-to-temp! dir-a)
        (write-to-temp! dir-b)
        (doseq [name ["candidate.jsonld" "expanded.json" "result.json"]]
          (is (= (seq (file-bytes (io/file dir-a name)))
                 (seq (file-bytes (io/file dir-b name))))
              (str name " must be byte-identical across two harness runs")))))))

(deftest context-hash-test
  (testing "context-hash is sha256 over the JCS canonical context bytes"
    (let [hex (hash/sha256-bytes
               (jcs/canonical-json-bytes (files/read-json context-path)))
          recomputed (str "sha256:" hex)
          committed (get (files/read-json result-path) "context_hash")]
      (is (= recomputed committed)
          "validation-result context_hash must match a recomputed hash")
      (is (= (la/context-hash context-path) committed)
          "la/context-hash on the real context must match the committed hash"))))

(deftest context-declares-canonical-abc-namespace-test
  (is (= "https://w3id.org/abc/"
         (get-in (files/read-json context-path) ["@context" "abc"]))))

(deftest expanded-artifact-id-uses-canonical-predicate-test
  (let [expanded (files/read-json expanded-path)
        manifest-id (get (files/read-json manifest-path) "artifact_id")]
    (is (= manifest-id
           (get-in expanded
                   ["expanded" 0 "https://w3id.org/abc/artifactId"
                    0 "@value"])))))

(deftest identity-invariant-test
  (testing "manifest artifact_id round-trips through expansion unchanged"
    (let [manifest-id (get (files/read-json manifest-path) "artifact_id")
          result (files/read-json result-path)
          inv (get result "identity_invariant")]
      (is (= manifest-id (get inv "manifest_artifact_id")))
      (is (= manifest-id (get inv "expanded_artifact_id"))
          "abc:artifactId must survive titanium expansion as a literal string")
      (is (true? (get inv "preserved_after_expansion")))
      (is (= "ok" (get result "status"))))))

(deftest harness-refuses-external-jsonld-fetches-test
  (testing "the harness refuses to fetch any URL other than the ABC public context"
    (let [other-context-doc (.getBytes "{\"@context\":\"https://example.invalid/other.jsonld\"}"
                                       "UTF-8")
          ctx (file-bytes (io/file context-path))]
      (is (thrown? Exception
                   (la/expand-document other-context-doc ctx
                                       "https://w3id.org/abc/test"))))))
