// build.rs runs once per Cargo invocation (when inputs change) and
// emits a Rust source fragment to OUT_DIR. The pedantic clippy
// lints the workspace applies to library code surface a lot of
// noise here that doesn't affect downstream builds — relax them
// at the file level.
#![allow(
    clippy::too_many_lines,
    clippy::redundant_clone,
    clippy::format_collect,
    clippy::missing_assert_message,
    clippy::absolute_paths,
    clippy::items_after_statements,
    reason = "build.rs is dev-tooling code that emits source to OUT_DIR; \
              the workspace's pedantic lint profile aimed at library APIs \
              fires noisy here without improving anything downstream"
)]
//! Compile-time gaiji table generator.
//!
//! Reads the three TSV data files in `data/`, runs `phf_codegen`
//! to build the perfect hashes, and writes the result to
//! `$OUT_DIR/jisx0213_table.rs`. The library `include!()`s that
//! file from `gaiji.rs`.
//!
//! ## Why `phf_codegen` instead of `phf::phf_map!`
//!
//! The macro form makes rustc do the perfect-hash construction at
//! macro-expansion time. For the 4 329-entry single-char map +
//! 8 883-entry description map (combined ~13 k entries) this costs
//! ~30–60 seconds of `cargo check` on cold caches and a noticeable
//! pause on every `rust-analyzer` reload. `phf_codegen` runs the
//! same algorithm at build-time inside `build.rs`; Cargo caches the
//! emitted file and only re-runs it when the input TSVs change, so
//! repeat-build cost drops to "include the cached `.rs`".
//!
//! The generated source uses `phf::Map<&'static str, ...>` —
//! identical runtime types to the macro path, so the lookup hot
//! path is unchanged.

use std::env;
use std::fs;
use std::io::{BufWriter, Write};
use std::path::PathBuf;

const INFALLIBLE: &str = "BufWriter::write_all over Vec<u8> is infallible";

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let data_dir = manifest_dir.join("data");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("jisx0213_table.rs");

    let single_tsv = data_dir.join("jisx0213-2004.tsv");
    let combo_tsv = data_dir.join("jisx0213-combo.tsv");
    let dict_tsv = data_dir.join("aozora-gaiji-chuki.tsv");
    let special_tsv = data_dir.join("aozora-gaiji-special.tsv");
    // Full mapping table — the slim TSVs above carry only 第3/第4水準, so
    // the reverse char → 水準 classifier (issue #89) needs the complete
    // file, which alone records the JIS X 0208 cells plus the
    // `[2000]/[2004]` / `Fullwidth:` / `Windows:` annotations.
    let std_txt = data_dir.join("jisx0213-2004-std.txt");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", single_tsv.display());
    println!("cargo:rerun-if-changed={}", combo_tsv.display());
    println!("cargo:rerun-if-changed={}", dict_tsv.display());
    println!("cargo:rerun-if-changed={}", special_tsv.display());
    println!("cargo:rerun-if-changed={}", std_txt.display());

    let single = parse_single_tsv(&single_tsv);
    let combo = parse_combo_tsv(&combo_tsv);
    let dict = parse_description_tsv(&dict_tsv);
    let special = parse_description_tsv(&special_tsv);
    let levels = build_level_table(&std_txt);

    // Hand-curated specials win on conflict — same precedence as
    // the previous `xtask gaiji-gen` path.
    let mut description: Vec<DescriptionEntry> = special.clone();
    let seen: std::collections::HashSet<String> =
        description.iter().map(|e| e.description.clone()).collect();
    for entry in dict {
        if !seen.contains(&entry.description) {
            description.push(entry);
        }
    }
    // Stable order across builds for diff readability if the file
    // is ever inspected by a human.
    description.sort_by(|a, b| a.description.cmp(&b.description));

    let plane1_count = single.iter().filter(|e| e.plane == 1).count();
    let plane2_count = single.iter().filter(|e| e.plane == 2).count();
    let combo_count = combo.len();
    let description_count = description.len();

    let file = fs::File::create(&out_path).expect("create OUT_DIR/jisx0213_table.rs");
    let mut out = BufWriter::new(file);

    writeln!(
        out,
        "// AUTO-GENERATED by `crates/aozora-encoding/build.rs`. \
         DO NOT EDIT BY HAND.\n\
         // Source TSVs in `crates/aozora-encoding/data/`; rerun by \
         touching any of them.\n",
    )
    .expect(INFALLIBLE);

    // ---- single-char map ----
    let mut single_builder = phf_codegen::Map::<&str>::new();
    let single_keys: Vec<String> = single
        .iter()
        .map(|e| mencode(e.plane, e.row, e.cell))
        .collect();
    let single_values: Vec<String> = single
        .iter()
        .map(|e| format!("'\\u{{{:04X}}}'", e.codepoint))
        .collect();
    for (k, v) in single_keys.iter().zip(single_values.iter()) {
        single_builder.entry(k.as_str(), v.as_str());
    }
    writeln!(
        out,
        "pub(crate) static JISX0213_MENCODE_TO_CHAR: phf::Map<&'static str, char> = {};",
        single_builder.build(),
    )
    .expect(INFALLIBLE);
    writeln!(out).expect(INFALLIBLE);

    // ---- combo (multi-codepoint) map ----
    let mut combo_builder = phf_codegen::Map::<&str>::new();
    let combo_keys: Vec<String> = combo
        .iter()
        .map(|e| mencode(e.plane, e.row, e.cell))
        .collect();
    let combo_values: Vec<String> = combo
        .iter()
        .map(|e| {
            let body: String = e
                .codepoints
                .iter()
                .map(|cp| format!("\\u{{{cp:04X}}}"))
                .collect();
            format!("\"{body}\"")
        })
        .collect();
    for (k, v) in combo_keys.iter().zip(combo_values.iter()) {
        combo_builder.entry(k.as_str(), v.as_str());
    }
    writeln!(
        out,
        "pub(crate) static JISX0213_MENCODE_TO_STR: phf::Map<&'static str, &'static str> = {};",
        combo_builder.build(),
    )
    .expect(INFALLIBLE);
    writeln!(out).expect(INFALLIBLE);

    // ---- description map ----
    // phf_codegen takes `&str` keys; the descriptions live in
    // `description[*].description` so we can borrow directly.
    // `phf_codegen` source-prints the keys with `Debug`, which
    // already escapes embedded `"` / `\` correctly.
    let mut description_builder = phf_codegen::Map::<&str>::new();
    let description_values: Vec<String> = description
        .iter()
        .map(|e| format!("'\\u{{{:04X}}}'", e.codepoint))
        .collect();
    for (entry, value) in description.iter().zip(description_values.iter()) {
        description_builder.entry(entry.description.as_str(), value.as_str());
    }
    writeln!(
        out,
        "pub(crate) static DESCRIPTION_TO_CHAR: phf::Map<&'static str, char> = {};",
        description_builder.build(),
    )
    .expect(INFALLIBLE);
    writeln!(out).expect(INFALLIBLE);

    // ---- reverse char → JIS 水準 table (issue #89) ----
    // A codepoint-sorted `&[(u32, u8)]` queried by binary search in
    // `suijun::jis_level`. A plain slice (not phf) keeps the codegen
    // dependency-free and is plenty fast for a per-char classifier.
    writeln!(
        out,
        "#[allow(dead_code, reason = \"queried by suijun::jis_level\")]\n\
         pub(crate) static JIS_LEVELS: &[(u32, u8)] = &[",
    )
    .expect(INFALLIBLE);
    for (codepoint, level) in &levels.entries {
        writeln!(out, "    ({codepoint:#08X}, {level}),").expect(INFALLIBLE);
    }
    writeln!(out, "];").expect(INFALLIBLE);
    writeln!(out).expect(INFALLIBLE);
    writeln!(
        out,
        "#[allow(dead_code, reason = \"pinned for level-table size tests\")]\n\
         pub(crate) const JISX0208_CELL_COUNT: usize = {jisx0208};\n\
         #[allow(dead_code, reason = \"pinned for level-table size tests\")]\n\
         pub(crate) const JIS_LEVEL3_CELL_COUNT: usize = {level3};\n\
         #[allow(dead_code, reason = \"pinned for level-table size tests\")]\n\
         pub(crate) const JIS_LEVEL4_CELL_COUNT: usize = {level4};",
        jisx0208 = levels.jisx0208_cells,
        level3 = levels.level3_cells,
        level4 = levels.level4_cells,
    )
    .expect(INFALLIBLE);
    writeln!(out).expect(INFALLIBLE);

    // ---- roman numeral tables (#326) ----
    // Bare `※［＃ローマ数字N］` glyph references have no men-ku-ten cell for
    // N≥13 (the corpus pairs them with a page-line ref, not a JIS code), so
    // they are composed from the U+2160 / U+2170 single-letter blocks.
    const ROMAN_MAX: u32 = 99;
    for (name, base) in [
        ("ROMAN_NUMERAL_UPPER", 0x2160u32),
        ("ROMAN_NUMERAL_LOWER", 0x2170u32),
    ] {
        let body: String = (0..=ROMAN_MAX)
            .map(|n| {
                let escaped: String = roman_numeral(n, base)
                    .chars()
                    .map(|c| format!("\\u{{{:04X}}}", c as u32))
                    .collect();
                format!("    \"{escaped}\",\n")
            })
            .collect();
        writeln!(
            out,
            "#[allow(dead_code, reason = \"indexed by gaiji::roman_numeral_glyph\")]\n\
             pub(crate) static {name}: [&str; {len}] = [\n{body}];",
            len = ROMAN_MAX + 1,
        )
        .expect(INFALLIBLE);
        writeln!(out).expect(INFALLIBLE);
    }

    // ---- count constants (used by tests) ----
    writeln!(
        out,
        "#[allow(dead_code, reason = \"pinned for table-size tests\")]\n\
         pub(crate) const JISX0213_PLANE1_COUNT: usize = {plane1_count};\n\
         #[allow(dead_code, reason = \"pinned for table-size tests\")]\n\
         pub(crate) const JISX0213_PLANE2_COUNT: usize = {plane2_count};\n\
         #[allow(dead_code, reason = \"pinned for table-size tests\")]\n\
         pub(crate) const JISX0213_COMBO_COUNT: usize = {combo_count};\n\
         #[allow(dead_code, reason = \"pinned for table-size tests\")]\n\
         pub(crate) const DESCRIPTION_COUNT: usize = {description_count};",
    )
    .expect(INFALLIBLE);
    writeln!(out).expect(INFALLIBLE);
    writeln!(
        out,
        "// Summary: 第3水準={plane1_count}, 第4水準={plane2_count}, \
         combo={combo_count}, description={description_count}, \
         total={total}.",
        total = plane1_count + plane2_count + combo_count + description_count,
    )
    .expect(INFALLIBLE);
}

#[derive(Clone, Copy)]
struct SingleEntry {
    plane: u8,
    row: u8,
    cell: u8,
    codepoint: u32,
}

struct ComboEntry {
    plane: u8,
    row: u8,
    cell: u8,
    codepoints: Vec<u32>,
}

#[derive(Clone)]
struct DescriptionEntry {
    description: String,
    codepoint: u32,
}

fn parse_single_tsv(path: &std::path::Path) -> Vec<SingleEntry> {
    let text =
        fs::read_to_string(path).unwrap_or_else(|err| panic!("read {}: {err}", path.display()));
    let mut out = Vec::new();
    for (lineno, line) in text.lines().enumerate() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let cols: Vec<&str> = trimmed.split('\t').collect();
        assert!(
            cols.len() == 4,
            "{}:{} expected 4 cols, got {}",
            path.display(),
            lineno + 1,
            cols.len(),
        );
        let plane: u8 = cols[0].parse().expect("plane");
        let row: u8 = cols[1].parse().expect("row");
        let cell: u8 = cols[2].parse().expect("cell");
        let codepoint = u32::from_str_radix(cols[3], 16).expect("codepoint hex");
        out.push(SingleEntry {
            plane,
            row,
            cell,
            codepoint,
        });
    }
    out
}

fn parse_combo_tsv(path: &std::path::Path) -> Vec<ComboEntry> {
    let text =
        fs::read_to_string(path).unwrap_or_else(|err| panic!("read {}: {err}", path.display()));
    let mut out = Vec::new();
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let cols: Vec<&str> = trimmed.split('\t').collect();
        assert_eq!(cols.len(), 4);
        let plane: u8 = cols[0].parse().expect("plane");
        let row: u8 = cols[1].parse().expect("row");
        let cell: u8 = cols[2].parse().expect("cell");
        let codepoints: Vec<u32> = cols[3]
            .split(',')
            .map(|hex| u32::from_str_radix(hex, 16).expect("codepoint hex"))
            .collect();
        out.push(ComboEntry {
            plane,
            row,
            cell,
            codepoints,
        });
    }
    out
}

fn parse_description_tsv(path: &std::path::Path) -> Vec<DescriptionEntry> {
    let text =
        fs::read_to_string(path).unwrap_or_else(|err| panic!("read {}: {err}", path.display()));
    let mut out = Vec::new();
    for line in text.lines() {
        let trimmed = line.trim_end();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let cols: Vec<&str> = trimmed.split('\t').collect();
        assert_eq!(cols.len(), 2);
        let codepoint = u32::from_str_radix(cols[1], 16).expect("codepoint hex");
        out.push(DescriptionEntry {
            description: cols[0].to_owned(),
            codepoint,
        });
    }
    out
}

/// Compose the standard roman numeral for `n` using the U+2160
/// (uppercase, `base` = `0x2160`) / U+2170 (lowercase, `0x2170`)
/// single-letter block atoms (I=+0, V=+4, X=+9, L=+12, C=+13, D=+14,
/// M=+15). Returns the empty string for `n == 0`. Emits the
/// `ROMAN_NUMERAL_*` tables consumed by `gaiji::roman_numeral_glyph`
/// for #326's bare `※［＃ローマ数字N］`.
fn roman_numeral(mut n: u32, base: u32) -> String {
    const TABLE: &[(u32, &[u32])] = &[
        (1000, &[15]),
        (900, &[13, 15]),
        (500, &[14]),
        (400, &[13, 14]),
        (100, &[13]),
        (90, &[9, 13]),
        (50, &[12]),
        (40, &[9, 12]),
        (10, &[9]),
        (9, &[0, 9]),
        (5, &[4]),
        (4, &[0, 4]),
        (1, &[0]),
    ];
    let mut s = String::new();
    for &(value, offsets) in TABLE {
        while n >= value {
            for &offset in offsets {
                s.push(char::from_u32(base + offset).expect("U+216x/217x is a valid scalar"));
            }
            n -= value;
        }
    }
    s
}

fn mencode(plane: u8, row: u8, cell: u8) -> String {
    let level = if plane == 1 { 3 } else { 4 };
    format!("第{level}水準{plane}-{row}-{cell}")
}

/// Reverse char → JIS 水準 table built from `jisx0213-2004-std.txt`
/// for issue #89's `jis_level` / `is_platform_dependent` classifier.
struct LevelTable {
    /// `(codepoint, level)` pairs sorted by codepoint, deduped so the
    /// lowest (most standard) level wins on collision. `level` ∈ 1..=4.
    entries: Vec<(u32, u8)>,
    /// plane-1 single cells NOT tagged `[2000]`/`[2004]` — the JIS X 0208
    /// set (第1 + 第2水準). Upstream-verified at 6918.
    jisx0208_cells: usize,
    /// plane-1 single cells tagged `[2000]`/`[2004]` — 第3水準.
    level3_cells: usize,
    /// plane-2 single cells — 第4水準.
    level4_cells: usize,
}

/// Insert keeping the lowest (most standard) level on collision — a
/// codepoint reachable as both a JIS X 0208 primary and a higher-level
/// alias is classified by its most-portable home.
fn insert_min(map: &mut std::collections::BTreeMap<u32, u8>, codepoint: u32, level: u8) {
    map.entry(codepoint)
        .and_modify(|cur| {
            if level < *cur {
                *cur = level;
            }
        })
        .or_insert(level);
}

/// Parse a single `U+XXXX` token to its scalar value. Returns `None`
/// for combining sequences (`U+XXXX+YYYY`) and malformed tokens.
fn parse_single_u_plus(token: &str) -> Option<u32> {
    let hex = token.trim().strip_prefix("U+")?;
    if hex.contains('+') {
        return None; // combining sequence — not a single char
    }
    u32::from_str_radix(hex, 16).ok()
}

/// Derive the reverse char → 水準 table from the full JIS X 0213:2004
/// mapping file. Each line is `JIS<TAB>Unicode<TAB># Name<TAB>Note…`:
///
/// * `JIS` = `N-RRCC` — plane digit `N` (1|2) then GL row/cell bytes.
/// * `Unicode` = `U+XXXX` (single) or `U+XXXX+YYYY` (combining, skipped).
/// * notes include `[2000]`/`[2004]` level tags and `Fullwidth:` /
///   `Windows:` alias annotations.
fn build_level_table(path: &std::path::Path) -> LevelTable {
    let text =
        fs::read_to_string(path).unwrap_or_else(|err| panic!("read {}: {err}", path.display()));
    let mut map: std::collections::BTreeMap<u32, u8> = std::collections::BTreeMap::new();
    let mut jisx0208_cells = 0usize;
    let mut level3_cells = 0usize;
    let mut level4_cells = 0usize;

    for line in text.lines() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut fields = line.split('\t');
        let jis = fields.next().expect("JIS column");
        let unicode = fields.next().unwrap_or("");
        let notes: Vec<&str> = fields.collect();

        // `N-RRCC`: GL prefix (`3-` = plane 1, `4-` = plane 2), then 4
        // hex digits (row byte, cell byte).
        let (prefix, code) = jis.split_once('-').expect("JIS code shaped `N-RRCC`");
        let plane: u8 = match prefix {
            "3" => 1,
            "4" => 2,
            other => panic!("unexpected JIS plane prefix {other:?} in {jis:?}"),
        };
        let row_byte = u8::from_str_radix(&code[0..2], 16).expect("row byte hex");

        let tagged_0213 = notes
            .iter()
            .any(|note| matches!(note.trim(), "[2000]" | "[2004]"));

        // plane 2 ⇒ 第4水準; plane-1 0213 addition ⇒ 第3水準; else
        // plane-1 JIS X 0208, split 第1|第2水準 at ku 47|48 — i.e. row
        // byte 0x4F|0x50, since ku = row_byte − 0x20.
        let level: u8 = if plane == 2 {
            4
        } else if tagged_0213 {
            3
        } else if row_byte <= 0x4F {
            1
        } else {
            2
        };

        // A combining sequence has a second `+` after the `U+` prefix.
        let is_combo = unicode
            .strip_prefix("U+")
            .is_some_and(|body| body.contains('+'));

        if !is_combo {
            match (plane, tagged_0213) {
                (1, false) => jisx0208_cells += 1,
                (1, true) => level3_cells += 1,
                (2, _) => level4_cells += 1,
                _ => {}
            }
            if let Some(codepoint) = parse_single_u_plus(unicode) {
                insert_min(&mut map, codepoint, level);
            }
        }

        // Register every `Fullwidth: U+YYYY` alias at the cell's level:
        // the primary is the ASCII form (e.g. `|` U+007C) but the
        // full-width form (｜ U+FF5C, a notation marker) is what appears
        // in real text and must classify as in-JIS. `Windows:` aliases
        // are deliberately NOT registered — they are the non-portable
        // CP932 variants that should surface as 機種依存文字.
        for note in &notes {
            if let Some(rest) = note.trim().strip_prefix("Fullwidth:")
                && let Some(codepoint) = parse_single_u_plus(rest)
            {
                insert_min(&mut map, codepoint, level);
            }
        }
    }

    LevelTable {
        entries: map.into_iter().collect(),
        jisx0208_cells,
        level3_cells,
        level4_cells,
    }
}
