(ns abc.tools.diagram.core
  "Effect-owning driver for committed, drift-checked diagrams. Each diagram is a
   value {:id :out-path :regen :build :lint}; :build is pure (-> flowchart input)
   and :lint is pure (-> problem strings). This module renders and gates them so
   the tier builders stay pure. See ADR 0029."
  (:require [clojure.java.io :as io]
            [abc.tools.diagram.mermaid :as mermaid]))

(defn render [{:keys [regen build]}]
  (str "%% GENERATED by " regen " — do not edit by hand; see ADR 0029\n"
       (mermaid/flowchart (build))))

(defn- drift [{:keys [out-path] :as d}]
  (let [want (render d)
        have (when (.exists (io/file out-path)) (slurp out-path))]
    (when (not= want have)
      (format "DRIFT: %s is stale; run `%s` to regenerate" out-path (:regen d)))))

(defn run!
  "Reconcile committed diagrams with their sources. Reads and (in write mode)
   writes, but does not print or exit — returns a result value the caller
   interprets. Writing is idempotent: identical sources produce identical bytes.
   :ok? is false on any lint problem, or (check mode) any drift."
  [diagrams {:keys [check?]}]
  (let [problems (vec (mapcat (fn [d] ((:lint d))) diagrams))]
    (cond
      (seq problems)
      {:ok? false :problems problems :drifts [] :wrote []}

      check?
      (let [drifts (vec (keep drift diagrams))]
        {:ok? (empty? drifts) :problems [] :drifts drifts :wrote []})

      :else
      {:ok? true :problems [] :drifts []
       :wrote (mapv (fn [{:keys [out-path] :as d}]
                      (spit out-path (render d))
                      out-path)
                    diagrams)})))
