(ns abc.tools.diagram.graphviz
  (:require [clojure.string :as str]))

(defn escape-html [value]
  (-> (str value)
      (str/replace "&" "&amp;")
      (str/replace "\"" "&quot;")
      (str/replace "<" "&lt;")
      (str/replace ">" "&gt;")))

(defn escape-dot [value]
  (-> (str value)
      (str/replace "\\" "\\\\")
      (str/replace "\"" "\\\"")
      (str/replace "\n" "\\n")))

(defn- id-string [value]
  (-> (name value)
      (str/replace #"[^A-Za-z0-9_]" "_")))

(defn- attr-value [value]
  (if (and (map? value) (contains? value :html))
    (:html value)
    (str "\"" (escape-dot value) "\"")))

(defn- attrs [m]
  (str "["
       (str/join ","
                 (for [[k v] (sort-by (comp name key) m)]
                   (str (name k) "=" (attr-value v))))
       "]"))

(defn- role-style [theme role]
  (cond
    (#{:identity :identity-formula :coordinate-family} role)
    {:color (:identity theme) :fontcolor (:text theme)}

    (#{:evidence :validation} role)
    {:color (:evidence theme) :fontcolor (:text theme)}

    (= :output role)
    {:color (:output theme) :fontcolor (:text theme)}

    :else
    {:color (:secondary theme) :fontcolor (:text theme)}))

(defn- html-label [{:keys [label subtitle coordinates]} theme]
  (str "<"
       "<TABLE BORDER=\"0\" CELLBORDER=\"0\" CELLPADDING=\"3\">"
       "<TR><TD><FONT POINT-SIZE=\"" (:primary-size theme) "\"><B>"
       (escape-html label) "</B></FONT></TD></TR>"
       (when subtitle
         (str "<TR><TD><FONT COLOR=\"" (:secondary theme)
              "\" POINT-SIZE=\"" (:secondary-size theme) "\">"
              (escape-html subtitle) "</FONT></TD></TR>"))
       (apply str
              (for [{:keys [label]} coordinates]
                (str "<TR><TD ALIGN=\"LEFT\"><FONT COLOR=\""
                     (:secondary theme) "\" POINT-SIZE=\""
                     (:secondary-size theme) "\">· "
                     (escape-html label) "</FONT></TD></TR>")))
       "</TABLE>>"))

(defn- node-line [node theme]
  (let [style (role-style theme (:role node))]
    (str "    \"" (id-string (:id node)) "\" "
         (attrs (merge {:label {:html (html-label node theme)}
                        :shape (if (= :validation (:role node)) "diamond" "rect")
                        :style "rounded"
                        :penwidth (:stroke-width theme)}
                       style))
         ";")))

(defn- edge-line [edge theme]
  (let [style (role-style theme (:role edge))]
    (str "  \"" (id-string (:from edge)) "\" -> \""
         (id-string (:to edge)) "\" "
         (attrs (merge
                 {:color (:color style)
                  :fontcolor (:secondary theme)
                  :fontname "Noto Sans CJK JP"
                  :fontsize (:secondary-size theme)
                  :penwidth (if (= :thick (:style edge))
                              4
                              (:stroke-width theme))
                  :style (if (= :dashed (:style edge)) "dashed" "solid")}
                 (when-let [label (:label edge)]
                   {:label label})))
         ";")))

(defn- id-collisions [nodes]
  (->> nodes
       (group-by (comp id-string :id))
       (keep (fn [[rendered matches]]
               (when (< 1 (count matches))
                 [rendered (mapv :id matches)])))
       (into {})))

(defn dot [{:keys [id direction theme groups nodes edges primary-order]}]
  (when-let [collisions (not-empty (id-collisions nodes))]
    (throw (ex-info "duplicate presentation node ids"
                    {:collisions collisions})))
  (let [grouped (group-by :group nodes)
        group-lines
        (mapcat
         (fn [{:keys [id label style]}]
           (concat
            [(str "  subgraph \"cluster_" (id-string id) "\" {")
             (str "    label=\"" (escape-dot label) "\";")
             (str "    color=\"" (:secondary theme) "\";")
             (str "    penwidth=\"" (:stroke-width theme) "\";")
             "    fontname=\"Noto Sans CJK JP\";"
             (str "    fontcolor=\"" (:secondary theme) "\";")
             (str "    fontsize=\"" (:secondary-size theme) "\";")
             (str "    style=\"rounded"
                  (when (= :dashed style) ",dashed") "\";")]
            (map #(node-line % theme)
                 (sort-by (comp id-string :id) (get grouped id)))
            ["  }"]))
         (sort-by (comp id-string :id) groups))
        ungrouped (sort-by (comp id-string :id) (get grouped nil))
        order-lines
        (for [[from to] (partition 2 1 primary-order)]
          (str "  \"" (id-string from) "\" -> \"" (id-string to)
               "\" [style=\"invis\",weight=\"100\"];"))]
    (str
     "// GENERATED by clojure -M:abc/presentation-diagrams — do not edit\n"
     "digraph \"" (id-string id) "\" {\n"
     "  graph " (attrs {:bgcolor "transparent"
                        :fontname "Noto Sans CJK JP"
                        :fontcolor (:text theme)
                        :nodesep "0.55"
                        :ranksep "0.85"
                        :pad "0.05"
                        :margin "0"
                        :rankdir direction
                        :splines "polyline"})
     ";\n"
     "  node " (attrs {:fontname "Noto Sans CJK JP"
                       :margin "0.20,0.14"})
     ";\n"
     "  edge " (attrs {:arrowsize "0.75"}) ";\n"
     (str/join "\n" group-lines) "\n"
     (when (seq ungrouped)
       (str (str/join "\n" (map #(node-line % theme) ungrouped)) "\n"))
     (when (seq order-lines)
       (str (str/join "\n" order-lines) "\n"))
     (str/join "\n"
               (map #(edge-line % theme)
                    (sort-by (juxt (comp id-string :from)
                                   (comp id-string :to)
                                   :label)
                             edges)))
     "\n}\n")))
