(ns abc.tools.diagram.workflow-graph
  "Tier 3: render one workflow-run.json as a runtime-provenance DAG. Per-run,
   printed to stdout, not committed. Edges connect a step that produces a target
   key to every step that requires it. See ADR 0029."
  (:require [abc.tools.diagram.mermaid :as mermaid]
            [abc.tools.json :as json]
            [abc.tools.schema :as schema]
            [abc.tools.workflow :as workflow]))

(def workflow-run-schema-path "schemas/workflow-run.schema.json")

(def ^:private status-class
  {"passed" "passed" "failed" "failed" "partial" "partial" "skipped" "skipped"})

(def ^:private class-defs
  {:passed "fill:#1b5e20,stroke:#a5d6a7,color:#fff"
   :failed "fill:#b71c1c,stroke:#ef9a9a,color:#fff"
   :partial "fill:#e65100,stroke:#ffcc80,color:#fff"
   :skipped "fill:#37474f,stroke:#b0bec5,color:#fff"})

(defn validation-problems [run]
  (let [schema-errors
        (or (schema/validation-errors
             (json/read-json-file workflow-run-schema-path) run)
            [])]
    (vec (concat schema-errors
                 (when (empty? schema-errors)
                   (workflow/validate-run run))))))

(defn- validate-run! [run]
  (when-let [errors (seq (validation-problems run))]
    (throw (ex-info "workflow-run is invalid"
                    {:kind :workflow-run-invalid
                     :errors (vec errors)})))
  run)

(defn run->graph [run]
  (validate-run! run)
  (let [steps (get run "steps")
        producers (reduce (fn [m s]
                            (reduce (fn [m k] (update m k (fnil conj #{}) (get s "id")))
                                    m (get s "produces")))
                          {} steps)]
    {:direction "TD"
     :nodes (for [s steps]
              {:id (get s "id")
               :label (str (get s "id") "<br/>[" (get s "status") "]")
               :class (get status-class (get s "status"))})
     :edges (distinct
             (for [s steps req (get s "requires") p (get producers req)
                   :when (not= p (get s "id"))]
               {:from p :to (get s "id") :label req :style :solid}))
     :class-defs class-defs}))

(defn run->mermaid [run]
  (str "%% GENERATED by clojure -M:abc/workflow-graph <run.json> — per-run; see ADR 0029\n"
       (mermaid/flowchart (run->graph run))))

(defn render-path [path]
  (run->mermaid (json/read-json-file path)))

(defn -main [& [path]]
  (if-not path
    (do
      (binding [*out* *err*]
        (println "usage: clojure -M:abc/workflow-graph <workflow-run.json>"))
      (System/exit 2))
    (try
      (print (render-path path))
      (flush)
      (catch clojure.lang.ExceptionInfo ex
        (binding [*out* *err*]
          (println "workflow-run validation failed:" path)
          (doseq [error (:errors (ex-data ex))]
            (println (pr-str error))))
        (System/exit 1)))))
