(ns abc.tools.diagram.workflow-graph
  "Tier 3: render one workflow-run.json as a runtime-provenance DAG. Per-run,
   printed to stdout, not committed. Edges connect a step that produces a target
   key to every step that requires it. See ADR 0029."
  (:require [abc.tools.json :as json]
            [abc.tools.diagram.mermaid :as mermaid]))

(def ^:private status-class
  {"passed" "passed" "failed" "failed" "partial" "partial" "skipped" "skipped"})

(def ^:private class-defs
  {:passed "fill:#1b5e20,stroke:#a5d6a7,color:#fff"
   :failed "fill:#b71c1c,stroke:#ef9a9a,color:#fff"
   :partial "fill:#e65100,stroke:#ffcc80,color:#fff"
   :skipped "fill:#37474f,stroke:#b0bec5,color:#fff"})

(defn run->graph [run]
  (let [steps (get run "steps")
        producers (reduce (fn [m s]
                            (reduce (fn [m k] (update m k (fnil conj #{}) (get s "id")))
                                    m (get s "produces")))
                          {} steps)]
    {:direction "TD"
     :nodes (for [s steps]
              {:id (get s "id")
               :label (str (get s "id") "<br/>[" (get s "status") "]")
               :class (get status-class (get s "status") "skipped")})
     :edges (distinct
             (for [s steps req (get s "requires") p (get producers req)
                   :when (not= p (get s "id"))]
               {:from p :to (get s "id") :label req :style :solid}))
     :class-defs class-defs}))

(defn run->mermaid [run]
  (str "%% GENERATED by clojure -M:abc/workflow-graph <run.json> — per-run; see ADR 0029\n"
       (mermaid/flowchart (run->graph run))))

(defn -main [path & _]
  (when-not path
    (binding [*out* *err*] (println "usage: clojure -M:abc/workflow-graph <workflow-run.json>"))
    (System/exit 2))
  (print (run->mermaid (json/read-json-file path)))
  (flush))
