//! Reverse JIS X 0208 / 0213 水準 (level) classification
//!
//! `aozora-encoding` already owns the full Project X0213 mapping table
//! and bakes the *forward* direction (注記 reference → `char`) into the
//! [`gaiji`](crate::gaiji) resolver. This module adds the *reverse*
//! query downstream character-level tooling needs: given a `char`,
//! which JIS 水準 is it, and may it appear literally in conformant
//! Aozora Bunko text or must it be a 外字注記?
//!
//! The table is generated by `build.rs` from `data/jisx0213-2004-std.txt`
//! and queried by binary search (see [`jis_level`]).
//!
//! ## Derivation
//!
//! * **第1 / 第2水準** ([`Suijun::Level1`] / [`Suijun::Level2`]) — plane-1
//!   cells *not* tagged `[2000]`/`[2004]`: the JIS X 0208 set (6918
//!   cells), split at ku 47 | 48.
//! * **第3水準** ([`Suijun::Level3`]) — plane-1 cells tagged
//!   `[2000]`/`[2004]` (JIS X 0213 additions).
//! * **第4水準** ([`Suijun::Level4`]) — plane-2 cells.
//! * **[`Suijun::Outside`]** — everything else: needs a 外字注記, or is a
//!   non-JIS / platform-dependent character.
//!
//! The full-width forms of the notation markers (｜＃［］, registered via
//! the table's `Fullwidth:` aliases) classify as in-JIS. The Windows
//! (CP932) variant codepoints do not, so they surface through
//! [`is_platform_dependent`].

use crate::jisx0213_table::{
    JIS_LEVEL3_CELL_COUNT, JIS_LEVEL4_CELL_COUNT, JIS_LEVELS, JISX0208_CELL_COUNT,
};

/// JIS X 0208 / 0213 水準 (level) of a character.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Suijun {
    /// 第1水準 — JIS X 0208 row 1–47 (basic symbols, kana, 第1水準漢字).
    Level1,
    /// 第2水準 — JIS X 0208 row 48–84 (第2水準漢字).
    Level2,
    /// 第3水準 — JIS X 0213 plane-1 additions (`[2000]`/`[2004]`).
    Level3,
    /// 第4水準 — JIS X 0213 plane 2.
    Level4,
    /// Outside JIS X 0208/0213 — must be a 外字注記 in conformant text,
    /// or is a non-JIS / platform-dependent character.
    Outside,
}

impl Suijun {
    /// Whether the level is within JIS X 0208 (第1水準 or 第2水準) — the
    /// portable core every conformant processor must handle.
    #[must_use]
    pub const fn is_jisx0208(self) -> bool {
        matches!(self, Self::Level1 | Self::Level2)
    }

    /// Whether the character is a JIS X 0213 addition beyond JIS X 0208
    /// (第3水準 or 第4水準) — representable in conformant Aozora text but
    /// outside the 0208 core.
    #[must_use]
    pub const fn is_jisx0213_extension(self) -> bool {
        matches!(self, Self::Level3 | Self::Level4)
    }

    /// Map the build-time `u8` level code (1..=4) to a [`Suijun`]; any
    /// other value (there is none today) degrades to [`Suijun::Outside`].
    const fn from_code(code: u8) -> Self {
        match code {
            1 => Self::Level1,
            2 => Self::Level2,
            3 => Self::Level3,
            4 => Self::Level4,
            _ => Self::Outside,
        }
    }
}

/// Classify a character's JIS X 0208 / 0213 水準.
///
/// Returns [`Suijun::Outside`] for any scalar not present in the
/// JIS X 0213:2004 table (half-width katakana, Hangul, emoji, the
/// Windows CP932 variant forms, …). Note that ASCII letters and digits
/// *are* in the table (the JIS X 0208 row-3 Latin cells), so they
/// classify as [`Suijun::Level1`], not `Outside`.
///
/// ```
/// use ab_aozora_encoding::{jis_level, Suijun};
/// assert_eq!(jis_level('亜'), Suijun::Level1); // 第1水準漢字
/// assert_eq!(jis_level('弌'), Suijun::Level2); // 第2水準漢字
/// assert!(jis_level('｜').is_jisx0208());       // full-width notation marker
/// assert_eq!(jis_level('\u{1F600}'), Suijun::Outside); // emoji
/// ```
#[must_use]
pub fn jis_level(c: char) -> Suijun {
    let key = c as u32;
    JIS_LEVELS
        .binary_search_by_key(&key, |&(codepoint, _)| codepoint)
        .map_or(Suijun::Outside, |idx| Suijun::from_code(JIS_LEVELS[idx].1))
}

/// Whether a character is a 機種依存文字: encodable in CP932
/// (Windows-31J / `Shift_JIS`) as a **double-byte** character but outside
/// JIS X 0208.
///
/// This is the classic "Windows 機種依存文字" set — NEC special
/// characters, NEC-selected IBM extensions, IBM extensions, and the
/// CP932 variant codepoints (e.g. U+FF5E full-width tilde). Single-byte
/// CP932 characters (ASCII, half-width katakana) are *not* flagged: the
/// JIS X 0208 contrast in the definition is about the double-byte
/// graphic set, and ASCII is already in JIS X 0208 via the table.
///
/// ```
/// use ab_aozora_encoding::is_platform_dependent;
/// assert!(is_platform_dependent('\u{FF5E}')); // CP932 full-width tilde variant
/// assert!(!is_platform_dependent('亜'));       // JIS X 0208
/// assert!(!is_platform_dependent('a'));        // ASCII (in JIS X 0208 via the table)
/// ```
#[must_use]
pub fn is_platform_dependent(c: char) -> bool {
    // In JIS X 0208 ⇒ portable, never platform-dependent. Checked first
    // so the common case skips the encode.
    if jis_level(c).is_jisx0208() {
        return false;
    }
    let mut buf = [0u8; 4];
    let encoded = c.encode_utf8(&mut buf);
    let (bytes, _, had_errors) = encoding_rs::SHIFT_JIS.encode(encoded);
    !had_errors && bytes.len() >= 2
}

/// `(第1+第2水準 cells, 第3水準 cells, 第4水準 cells)` baked into the
/// reverse table. Surfaced for the gatekeeper size pins (see
/// `tests/gatekeeper.rs`); not part of the everyday classifier surface.
#[must_use]
pub fn level_table_sizes() -> (usize, usize, usize) {
    (
        JISX0208_CELL_COUNT,
        JIS_LEVEL3_CELL_COUNT,
        JIS_LEVEL4_CELL_COUNT,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn levels_of_representative_characters() {
        assert_eq!(jis_level('亜'), Suijun::Level1); // 3-3021 第1水準漢字
        assert_eq!(jis_level('弌'), Suijun::Level2); // 3-5021 第2水準漢字
        assert_eq!(jis_level('\u{4FF1}'), Suijun::Level3); // 3-2E21 [2004]
        assert_eq!(jis_level('\u{4E02}'), Suijun::Level4); // 4-2122 plane 2
    }

    #[test]
    fn ascii_is_in_jis_x_0208_via_the_row3_latin_cells() {
        // The table maps the JIS row-3 Latin cells to the ASCII forms as
        // primaries (3-2361 → U+0061), so ASCII classifies as 第1水準.
        assert_eq!(jis_level('a'), Suijun::Level1);
        assert!(jis_level('a').is_jisx0208());
    }

    #[test]
    fn outside_covers_non_jis_scalars() {
        assert_eq!(jis_level('\u{1F600}'), Suijun::Outside); // emoji
        assert_eq!(jis_level('\u{AC00}'), Suijun::Outside); // Hangul 가
        assert_eq!(jis_level('\u{FF71}'), Suijun::Outside); // half-width katakana ｱ
    }

    #[test]
    fn full_width_notation_markers_resolve_via_fullwidth_aliases() {
        // ｜＃［］ exist in the table only as `Fullwidth:` aliases of the
        // ASCII primaries; they must still classify as in-JIS.
        for marker in ['｜', '＃', '［', '］'] {
            assert!(
                jis_level(marker).is_jisx0208(),
                "marker {marker:?} must classify as JIS X 0208",
            );
        }
    }

    #[test]
    fn platform_dependent_predicate() {
        // CP932 double-byte variant outside JIS X 0208 ⇒ platform-dependent.
        assert!(is_platform_dependent('\u{FF5E}')); // full-width tilde
        // JIS X 0208 / ASCII ⇒ portable.
        assert!(!is_platform_dependent('亜'));
        assert!(!is_platform_dependent('a'));
        // Single-byte CP932 (half-width katakana) ⇒ not flagged.
        assert!(!is_platform_dependent('\u{FF71}'));
        // Not CP932-encodable at all ⇒ not flagged.
        assert!(!is_platform_dependent('\u{1F600}'));
    }

    #[test]
    fn is_jisx0213_extension_partitions_with_is_jisx0208() {
        assert!(Suijun::Level1.is_jisx0208());
        assert!(Suijun::Level2.is_jisx0208());
        assert!(Suijun::Level3.is_jisx0213_extension());
        assert!(Suijun::Level4.is_jisx0213_extension());
        assert!(!Suijun::Outside.is_jisx0208());
        assert!(!Suijun::Outside.is_jisx0213_extension());
    }
}
