[package]
name = "ab-parser-rq-source-accountability"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
ab-aozora-aat = { path = "../ab-aozora-aat" }
ab-diff-utils = { path = "../ab-diff-utils" }
anyhow.workspace = true
clap.workspace = true
jsonschema.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
hegeltest = "0.28"
