import importlib.util
import json
from collections import Counter
from pathlib import Path

import pytest


ROOT = Path(__file__).parents[1]
SUMMARY = ROOT / "runs/aozora-parser-neutral-comparison-2026-07/run-manifests.json"
PREREGISTRATION = ROOT.parents[1] / "docs/studies/aozora-parser-comparison-preregistration.json"
NEUTRAL_EXECUTOR = ROOT / "neutral_executor.py"
SPEC = importlib.util.spec_from_file_location(
    "freeze_run_evidence", ROOT / "freeze_run_evidence.py"
)
assert SPEC is not None and SPEC.loader is not None
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


def _authentic_external_run(tmp_path: Path) -> tuple[dict, dict, Path]:
    """Produce a real one-item run and the summary+resolver that bind to it.

    Everything is self-consistent because the run is generated by the real
    neutral executor: the manifest, outcome, execution, materialization, and
    program hashes all agree. `verify_external` must accept it, and must reject
    any single mutation (e.g. an inflated outcome count).
    """
    neutral = MODULE.load_neutral_executor(NEUTRAL_EXECUTOR)
    sources = tmp_path / "sources"
    sources.mkdir()
    body = b"hello world"
    (sources / "a.txt").write_bytes(body)
    inventory_path = tmp_path / "inventory.json"
    inventory_path.write_text(
        json.dumps({"items": [{"id": "work-a", "path": "a.txt", "sha256": MODULE.sha256(body)}]})
    )
    program = tmp_path / "prog"
    program.write_text("#!/bin/sh\nexec cat\n")
    program.chmod(0o755)
    command = [str(program)]

    output = tmp_path / "run"
    neutral.execute(inventory_path, sources, command, output, 5, 1)
    manifest_bytes = (output / "manifest.json").read_bytes()
    execution_sha = json.loads(manifest_bytes)["execution_sha256"]
    outcomes = dict(
        sorted(Counter(row["status"] for row in neutral.verify(inventory_path, output)).items())
    )

    materialization = {
        "candidate": "ab-aozora",
        "mode": "native",
        "parser_revision": "rev-1",
        "adapter_revision": None,
        "program_sha256": MODULE.sha256(program.read_bytes()),
        "derivation_identity": "/nix/store/deadbeef-ab-aozora",
    }
    projection = {
        k: materialization[k]
        for k in (
            "candidate",
            "mode",
            "parser_revision",
            "adapter_revision",
            "program_sha256",
            "derivation_identity",
        )
    }
    summary = {
        "runs": [
            {
                "candidate": "ab-aozora",
                "mode": "native",
                "inventory": "inv",
                "artifact_root": "root",
                "execution_sha256": execution_sha,
                "manifest_sha256": MODULE.sha256(manifest_bytes),
                "outcomes": outcomes,
            }
        ],
        "candidates": {"ab-aozora": {"parser_revision": "rev-1", "adapter_revision": None}},
        "execution_contracts": {
            execution_sha: {
                "candidate": "ab-aozora",
                "mode": "native",
                "required_program_basename": "prog",
                "required_argv": [],
                "materialization_binding_sha256": MODULE.sha256(MODULE.canonical_bytes(projection)),
            }
        },
    }
    resolver = {
        "inventories": {"inv": str(inventory_path)},
        "artifact_roots": {"root": str(output)},
        "executions": {execution_sha: {"command": command, "environment": {}}},
        "materializations": {execution_sha: materialization},
    }
    return summary, resolver, NEUTRAL_EXECUTOR


def test_verify_external_accepts_an_authentic_run(tmp_path: Path) -> None:
    summary, resolver, executor = _authentic_external_run(tmp_path)
    # No raise: the committed counts and provenance hashes bind to the real run.
    MODULE.verify_external_bindings(summary, resolver, executor)


def test_verify_external_rejects_a_tampered_outcome_count(tmp_path: Path) -> None:
    summary, resolver, executor = _authentic_external_run(tmp_path)
    outcomes = summary["runs"][0]["outcomes"]
    outcomes[next(iter(outcomes))] += 1  # inflate a recorded count
    with pytest.raises(ValueError, match="external outcome counts mismatch"):
        MODULE.verify_external_bindings(summary, resolver, executor)


def test_verify_external_rejects_a_tampered_program_hash(tmp_path: Path) -> None:
    summary, resolver, executor = _authentic_external_run(tmp_path)
    execution_sha = summary["runs"][0]["execution_sha256"]
    resolver["materializations"][execution_sha]["program_sha256"] = "sha256:" + "0" * 64
    with pytest.raises(ValueError, match="materialization binding mismatch"):
        MODULE.verify_external_bindings(summary, resolver, executor)


def load_summary() -> dict[str, object]:
    return json.loads(SUMMARY.read_bytes())


def test_checked_summary_has_exact_closed_lane_matrix() -> None:
    MODULE.validate_summary(load_summary())


def test_missing_lane_is_rejected() -> None:
    summary = load_summary()
    runs = summary["runs"]
    assert isinstance(runs, list)
    runs.pop()
    with pytest.raises(ValueError, match="exact 20-lane matrix"):
        MODULE.validate_summary(summary)


def test_host_capture_must_be_closed_unavailable_classification() -> None:
    summary = load_summary()
    summary["host_capture"] = {"status": "unavailable"}
    with pytest.raises(ValueError, match="host capture"):
        MODULE.validate_summary(summary)


def test_command_must_correspond_to_candidate_and_mode() -> None:
    summary = load_summary()
    runs = summary["runs"]
    assert isinstance(runs, list) and isinstance(runs[0], dict)
    execution = runs[0]["execution_sha256"]
    contracts = summary["execution_contracts"]
    assert isinstance(contracts, dict) and isinstance(contracts[execution], dict)
    contracts[execution]["candidate"] = "aozora2"
    with pytest.raises(ValueError, match="command binding"):
        MODULE.validate_summary(summary)


def test_canonical_bytes_are_byte_identical() -> None:
    checked = SUMMARY.read_bytes()
    assert MODULE.canonical_bytes(load_summary()) == checked


def test_protocol_mutation_is_rejected() -> None:
    preregistration = PREREGISTRATION.read_bytes().replace(
        b'"schema_version": 1', b'"schema_version": 2'
    )
    with pytest.raises(ValueError, match="protocol hash"):
        MODULE.validate_frozen_bindings(preregistration, load_summary(), {})


@pytest.mark.parametrize(
    ("field", "value", "message"),
    [
        ("study_id", "wrong-study", "study id"),
        ("timeout_seconds", 299, "timeout"),
    ],
)
def test_summary_frozen_scalar_mutation_is_rejected(
    field: str, value: object, message: str
) -> None:
    summary = load_summary()
    summary[field] = value
    with pytest.raises(ValueError, match=message):
        MODULE.validate_frozen_bindings(PREREGISTRATION.read_bytes(), summary, {})


def test_candidate_revision_mutation_is_rejected() -> None:
    summary = load_summary()
    candidates = summary["candidates"]
    assert isinstance(candidates, dict) and isinstance(candidates["aozora2"], dict)
    candidates["aozora2"]["parser_revision"] = "wrong"
    with pytest.raises(ValueError, match="candidate revisions"):
        MODULE.validate_frozen_bindings(PREREGISTRATION.read_bytes(), summary, {})


def test_inventory_content_hash_and_count_mutation_is_rejected(tmp_path: Path) -> None:
    inventory = tmp_path / "inventory.json"
    inventory.write_text(
        '{"items": [{"id": "one", "path": "one.txt", "sha256": "sha256:' + "0" * 64 + '"}]}'
    )
    summary = load_summary()
    summary_inventories = summary["inventories"]
    assert isinstance(summary_inventories, dict)
    summary_inventories["official-notation-vectors"] = {
        **summary_inventories["official-notation-vectors"],
        "items": 2,
    }
    with pytest.raises(ValueError, match="inventory hash or count"):
        MODULE.validate_frozen_bindings(
            PREREGISTRATION.read_bytes(),
            summary,
            {"official-notation-vectors": inventory},
        )
