[package]
name = "ab-ortho-detect"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
ab-plaintext = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
ab-plaintext = { workspace = true }
ab-morph-analyzers = { workspace = true }
serde_json = { workspace = true }
