{ pkgs, odd }:

let
  teiP5Version = "4.11.0";

  teiAllSchema = pkgs.fetchurl {
    url = "https://www.tei-c.org/Vault/P5/${teiP5Version}/xml/tei/custom/schema/relaxng/tei_all.rng";
    hash = "sha256-7MSfAMN/SQtd9xa2cuPbpjXrHknM2I+5aYWUmN9CwIQ=";
  };

  teiStylesheets = pkgs.fetchzip {
    url = "https://github.com/TEIC/Stylesheets/releases/download/v7.60.0/tei-xsl-7.60.0.zip";
    hash = "sha256-KcDZmMNtJHFbaBlTgr37Yy6O6J/QLDcoAG20CmBDpKk=";
    stripRoot = false;
  };

  teiP5Subset = pkgs.fetchurl {
    url = "https://www.tei-c.org/Vault/P5/${teiP5Version}/xml/tei/odd/p5subset.xml";
    hash = "sha256-r9HruHPKcY1hvly09hFkoRA3/gybYSomI+avGvGe8wE=";
  };

  artifacts =
    pkgs.runCommand "abc-tei-profile-artifacts"
      {
        nativeBuildInputs = [
          pkgs.saxon-he
          pkgs.gnused
        ];
      }
      ''
        set -euo pipefail
        cp ${odd} tei-profile.odd
        saxon-he -s:tei-profile.odd \
          -xsl:${teiStylesheets}/xml/tei/stylesheet/odds/odd2odd.xsl \
          -o:expanded.odd \
          defaultSource=${teiP5Subset}
        saxon-he -s:expanded.odd \
          -xsl:${teiStylesheets}/xml/tei/stylesheet/odds/odd2relax.xsl \
          -o:tei-profile.rng
        saxon-he -s:expanded.odd \
          -xsl:${teiStylesheets}/xml/tei/stylesheet/odds/extract-isosch.xsl \
          -o:tei-profile.sch \
          lang=en
        # Build-artifact canonicalization (ADR 0012). Narrow rewrites; the
        # ODD remains source of truth.
        # 1. Strip non-deterministic generation timestamps so rebuilds are
        #    byte-stable.
        # 2. Rewrite ABC pattern IDs from
        #    `schematron-constraint-<ident>-<seq>` back to the `<ident>` the
        #    ODD's constraintSpec/@ident declared. Inherited TEI built-in
        #    pattern IDs are left untouched.
        sed -E -i 's|Schema generated from ODD source [0-9TZ:.+-]+\. \. ?|Schema generated from ODD source. |' tei-profile.rng
        sed -E -i "s|<!-- This file generated [0-9TZ:.+-]+ by 'extract-isosch.xsl'. -->|<!-- This file generated by 'extract-isosch.xsl'. -->|" tei-profile.sch
        sed -E -i 's|id="schematron-constraint-(abc-[a-z0-9-]+)-[0-9]+"|id="\1"|g' tei-profile.sch
        sed -E -i 's|id="abc-tei-v0-(abc-[a-z0-9-]+)-constraint-rule-[0-9]+"|id="\1"|g' tei-profile.sch tei-profile.rng
        # Drop inherited TEI built-in patterns that the ODD did not declare.
        # The committed v0 Schematron artifact is the ABC profile policy
        # surface; inherited TEI diagnostics remain out-of-scope until ABC
        # explicitly adopts them. This also preserves compatibility with
        # ph-schematron's stricter pure ISO model, which rejects the inherited
        # TEI sch:let / role="nonfatal" constructs even though the XSLT path can
        # execute them.
        awk '
          /^   <pattern id="schematron-constraint-/ { drop = 1 }
          !drop { print }
          drop && /^   <\/pattern>/ { drop = 0 }
        ' tei-profile.sch > tei-profile.sch.filtered
        mv tei-profile.sch.filtered tei-profile.sch
        mkdir -p "$out"
        cp tei-profile.rng tei-profile.sch "$out/"
      '';
in
{
  version = teiP5Version;
  inherit
    teiAllSchema
    teiStylesheets
    teiP5Subset
    artifacts
    ;
}
