<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt2">
   <title>ISO Schematron rules</title>
   <!-- This file generated by 'extract-isosch.xsl'. -->
   <!-- ********************* -->
   <!-- namespaces, declared: -->
   <!-- ********************* -->
   <ns prefix="tei" uri="http://www.tei-c.org/ns/1.0"/>
   <ns prefix="tei" uri="http://www.tei-c.org/ns/1.0"/>
   <ns prefix="xs" uri="http://www.w3.org/2001/XMLSchema"/>
   <ns prefix="rng" uri="http://relaxng.org/ns/structure/1.0"/>
   <ns prefix="rna" uri="http://relaxng.org/ns/compatibility/annotations/1.0"/>
   <ns prefix="sch" uri="http://purl.oclc.org/dsdl/schematron"/>
   <ns prefix="sch1x" uri="http://www.ascc.net/xml/schematron"/>
   <!-- ******************************************************* -->
   <!-- constraints in en, und, mul, zxx, of which there are 80 -->
   <!-- ******************************************************* -->
   <pattern id="abc-tei-header-title">
      <rule context="tei:teiHeader">
         <assert test="tei:fileDesc/tei:titleStmt/tei:title[not(@type = 'sub')]"> ABC TEI requires a main title in teiHeader/fileDesc/titleStmt.</assert>
      </rule>
   </pattern>
   <pattern id="abc-tei-header-source-work-id">
      <rule context="tei:teiHeader">
         <assert test=".//tei:idno[@type = ('aozora-work-id', 'source-work-id')]"> ABC TEI requires an Aozora work ID or source work identifier.</assert>
      </rule>
   </pattern>
   <pattern id="abc-ruby-complete">
      <rule context="tei:ruby">
         <assert test="tei:rb and tei:rt"> ABC TEI ruby requires both rb and rt components.</assert>
      </rule>
   </pattern>
   <pattern id="abc-gaiji-reference">
      <rule context="tei:g">
         <assert test="@ref or @corresp or @ana"> ABC TEI gaiji requires a declaration reference, source marker reference, or resolution status.</assert>
      </rule>
   </pattern>
   <pattern id="abc-figure-accessibility">
      <rule context="tei:figure">
         <report role="warning" test="not(tei:figDesc or tei:head or tei:p)"> ABC TEI figure should preserve a figDesc, head, or caption paragraph when available.</report>
      </rule>
   </pattern>
   <pattern id="abc-source-span-reference">
      <rule context="*[@source]">
         <assert test="every $s in tokenize(normalize-space(@source), '\s+') satisfies starts-with($s, '#')"> ABC TEI source span references must point to local span identifiers.</assert>
      </rule>
   </pattern>
   <pattern id="abc-transcription-vs-annotation">
      <rule context="tei:text//tei:w | tei:text//tei:m | tei:text//tei:pc">
         <assert role="warning"
                 test="ancestor::tei:TEI/tei:teiHeader//tei:encodingDesc//tei:tagsDecl//tei:namespace[@name = 'http://www.tei-c.org/ns/1.0']/tei:tagUsage/@gi = local-name()"> ABC TEI linguistic enrichment in the transcription layer must be declared in the header.</assert>
      </rule>
   </pattern>
</schema>
