[package]
name = "ab-compare"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ab-diff-utils.workspace = true
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
rustc-hash.workspace = true
walkdir.workspace = true

[dev-dependencies]
criterion.workspace = true
tempfile.workspace = true

[[bench]]
name = "aat_diff"
harness = false
